### ISSUE TITLE
Android app crashes on bank authentication but iOS works properly

### ISSUE THREAD

**Issue by mohitmarfatia** [flutter-stripe/flutter_stripe#1051]
**Describe the bug**
When I try to do handle next action on android, after tapping "Complete Authentication", app crashes. It's working perfectly for iOS.

**To Reproduce**
1. Entering number 4000002760003184 into the cardfield.
2. Tapping the confirm button.
3. Tapping complete authentication button

Code used after retrieving client secret:
`final paymentIntent =
            await Stripe.instance.handleNextAction(clientSecret);
        if (paymentIntent.status == PaymentIntentsStatus.RequiresConfirmation) {
          Map<String, dynamic> results = await _callPayEndpointIntentId(
            paymentIntentId: paymentIntent.id,
          ); 
        }
`

**Expected behavior**
User authenticates and the payment is accepted

**Smartphone / tablet**
 - Device: Pixel 5
 - OS: Android 12
 - Package version: 7.0.0
 - Flutter version 3.3.6

Logs:
`W/m.flutter.app(24941): Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (unsupported, reflection, allowed)
W/m.flutter.app(24941): Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (unsupported, reflection, allowed)
D/EGL_emulation(24941): app_time_stats: avg=4.56ms min=2.54ms max=32.65ms count=54
I/WebViewFactory(24941): Loading com.google.android.webview version 91.0.4472.114 (code 447211484)
W/m.flutter.app(24941): Accessing hidden method Landroid/os/Trace;->isTagEnabled(J)Z (unsupported, reflection, allowed)
W/m.flutter.app(24941): Accessing hidden method Landroid/os/Trace;->traceBegin(JLjava/lang/String;)V (unsupported, reflection, allowed)
W/m.flutter.app(24941): Accessing hidden method Landroid/os/Trace;->traceEnd(J)V (unsupported, reflection, allowed)
W/m.flutter.app(24941): Accessing hidden method Landroid/os/Trace;->asyncTraceBegin(JLjava/lang/String;I)V (unsupported, reflection, allowed)
W/m.flutter.app(24941): Accessing hidden method Landroid/os/Trace;->asyncTraceEnd(JLjava/lang/String;I)V (unsupported, reflection, allowed)
I/cr_VariationsUtils(24941): Failed reading seed file "/data/user/0/com.flutter.app/app_webview/variations_seed_new"
I/cr_VariationsUtils(24941): Failed reading seed file "/data/user/0/com.flutter.app/app_webview/variations_seed"
I/cr_LibraryLoader(24941): Loaded native library version number "91.0.4472.114"
I/cr_CachingUmaRecorder(24941): Flushed 6 samples from 6 histograms.
D/CompatibilityChangeReporter(24941): Compat change id reported: 171228096; UID 10147; state: ENABLED
W/m.flutter.app(24941): Accessing hidden method Landroid/media/AudioManager;->getOutputLatency(I)I (unsupported, reflection, allowed)
D/HostConnection(24941): createUnique: call
D/HostConnection(24941): HostConnection::get() New Host Connection established 0xb400007a9fc68a50, tid 25118
D/HostConnection(24941): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV_Cache ANDROID_EMU_vulkan_ignored_handles ANDROID_EMU_has_shared_slots_host_memory_allocator ANDROID_EMU_vulkan_free_memory_sync ANDROID_EMU_vulkan_shader_float16_int8 ANDROID_EMU_vulkan_async_queue_submit ANDROID_EMU_vulkan_queue_submit_with_commands ANDROID_EMU_sync_buffer_data ANDROID_EMU_read_color_buffer_dma GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_gles_max_version_3_0 
D/EGL_emulation(24941): eglCreateContext: 0xb400007a9fc69e90: maj 3 min 0 rcv 3
D/EGL_emulation(24941): eglMakeCurrent: 0xb400007a9fc69e90: ver 3 0 (tinfo 0x7cb9f5d280) (first time)
W/cr_media(24941): Requires BLUETOOTH permission
D/EGL_emulation(24941): eglCreateContext: 0xb400007a9fc69e90: maj 3 min 0 rcv 3
I/m.flutter.app(24941): Background young concurrent copying GC freed 87362(5543KB) AllocSpace objects, 7(268KB) LOS objects, 38% free, 8123KB/12MB, paused 2.388ms,24us total 239.450ms
D/EGL_emulation(24941): app_time_stats: avg=9.59ms min=3.06ms max=72.46ms count=51
D/EGL_emulation(24941): eglCreateContext: 0xb400007a9fc69410: maj 3 min 0 rcv 3
D/EGL_emulation(24941): app_time_stats: avg=7.94ms min=2.42ms max=102.91ms count=51
I/chromium(24941): [INFO:CONSOLE(273)] "Refused to load the stylesheet 'https://fast.fonts.net/t/1.css?apiType=css&projectid=4414faae-0f1e-48be-9319-851fc710f613' because it violates the following Content Security Policy directive: "style-src 'unsafe-inline' 'self' https://b.stripecdn.com https://files.stripe.com https://cloud.typography.com/711858/764882/css/fonts.css". Note that 'style-src-elem' was not explicitly set, so 'style-src' is used as a fallback.
I/chromium(24941): ", source: https://stripe.com/sources/test_source_3ds?livemode=false&type=three_d_secure&pass_through=&return_url=https%3A%2F%2Fhooks.stripe.com%2Fthree_d_secure%2Fredirect_complete%2Facct_1LZgSeFacQ1hP4w9%2Ftdsrc_1MA9aOFacQ1hP4w9e1eeTtey&source_slug=CBsaFwoVYWNjdF8xTFpnU2VGYWNRMWhQNHc5KIj3oZwGMgZp0Na4AfU6LdjiM6IoF-ZBmZ0j1OXrTrb6CHAUzdJrrLu_R3ZPY7BhjL70yed34h6cFRQl1w&amount=899&currency=eur&usage=single_use (273)
D/EGL_emulation(24941): app_time_stats: avg=47.16ms min=2.32ms max=2027.11ms count=46
D/EGL_emulation(24941): app_time_stats: avg=618.62ms min=104.85ms max=1132.39ms count=2
D/EGL_emulation(24941): app_time_stats: avg=4.33ms min=3.77ms max=9.48ms count=57
D/EGL_emulation(24941): app_time_stats: avg=54.08ms min=3.73ms max=1570.99ms count=32
D/EGL_emulation(24941): app_time_stats: avg=37.96ms min=4.36ms max=596.02ms count=21
W/cr_AwContents(24941): Application attempted to call on a destroyed WebView
W/cr_AwContents(24941): java.lang.Throwable
W/cr_AwContents(24941): 	at org.chromium.android_webview.AwContents.r(chromium-TrichromeWebViewGoogle6432.apk-stable-447211484:2)
W/cr_AwContents(24941): 	at Sa.loadingStateChanged(chromium-TrichromeWebViewGoogle6432.apk-stable-447211484:2)
W/cr_AwContents(24941): 	at android.os.MessageQueue.nativePollOnce(Native Method)
W/cr_AwContents(24941): 	at android.os.MessageQueue.next(MessageQueue.java:335)
W/cr_AwContents(24941): 	at android.os.Looper.loopOnce(Looper.java:161)
W/cr_AwContents(24941): 	at android.os.Looper.loop(Looper.java:288)
W/cr_AwContents(24941): 	at android.app.ActivityThread.main(ActivityThread.java:7839)
W/cr_AwContents(24941): 	at java.lang.reflect.Method.invoke(Native Method)
W/cr_AwContents(24941): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
W/cr_AwContents(24941): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
E/AndroidRuntime(24941): FATAL EXCEPTION: DefaultDispatcher-worker-2
E/AndroidRuntime(24941): Process: com.flutter.app, PID: 24941
E/AndroidRuntime(24941): java.lang.NoSuchFieldError: No static field UpiAwaitNotification of type Lcom/stripe/android/model/StripeIntent$NextActionType; in class Lcom/stripe/android/model/StripeIntent$NextActionType; or its superclasses (declaration of 'com.stripe.android.model.StripeIntent$NextActionType' appears in /data/app/~~GkKIlIbnVXuMUbLPLntfcw==/com.flutter.app-jrAPKxRXCpeFvIoJmZqhgg==/base.apk!classes8.dex)
E/AndroidRuntime(24941): 	at com.reactnativestripesdk.MappersKt$WhenMappings.<clinit>(Unknown Source:679)
E/AndroidRuntime(24941): 	at com.reactnativestripesdk.MappersKt.mapIntentStatus(Mappers.kt:34)
E/AndroidRuntime(24941): 	at com.reactnativestripesdk.MappersKt.mapFromPaymentIntentResult(Mappers.kt:407)
E/AndroidRuntime(24941): 	at com.reactnativestripesdk.PaymentLauncherFragment$retrievePaymentIntent$1.onSuccess(PaymentLauncherFragment.kt:223)
E/AndroidRuntime(24941): 	at com.reactnativestripesdk.PaymentLauncherFragment$retrievePaymentIntent$1.onSuccess(PaymentLauncherFragment.kt:211)
E/AndroidRuntime(24941): 	at com.stripe.android.Stripe$dispatchResult$2.invokeSuspend(Stripe.kt:1801)
E/AndroidRuntime(24941): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
E/AndroidRuntime(24941): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
E/AndroidRuntime(24941): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime(24941): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(24941): 	at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime(24941): 	at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime(24941): 	at android.app.ActivityThread.main(ActivityThread.java:7839)
E/AndroidRuntime(24941): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(24941): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime(24941): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
E/AndroidRuntime(24941): 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@2570279, Dispatchers.IO]
I/Process (24941): Sending signal. PID: 24941 SIG: 9
Lost connection to device.
`

**Comment by jamesblasco** [comment]
Could you do `flutter clean`and try again?. It looks that is not finding the `UpiAwaitNotification` type that we started using in the latest update. This might be because the flutter cache is using an already minimised version of the android dependencies where this was not used before

**Comment by Naveed44** [comment]
The same error with `UpiAwaitNotification` appears when `CardFormField` component fills completely on Android. The app dies completely, dies as soon as the form is completed (like, putting the last digit in Zip Code)
Already tried `flutter clean` but nothing.

The logs:
`E/AndroidRuntime( 7287): FATAL EXCEPTION: main
E/AndroidRuntime( 7287): Process: com.example.myapp, PID: 7287
E/AndroidRuntime( 7287): java.lang.NoSuchFieldError: No static field UpiAwaitNotification of type Lcom/stripe/android/model/StripeIntent$NextActionType; in class Lcom/stripe/android/model/StripeIntent$NextActionType; or its superclasses (declaration of 'com.stripe.android.model.StripeIntent$NextActionType' appears in /data/app/com.example.my_spalive-LbAWLJ5zPxUpFq1706J59g==/base.apk!classes7.dex)
E/AndroidRuntime( 7287): 	at com.reactnativestripesdk.utils.MappersKt$WhenMappings.<clinit>(Unknown Source:689)
E/AndroidRuntime( 7287): 	at com.reactnativestripesdk.utils.MappersKt.mapCardBrand(Mappers.kt:90)
E/AndroidRuntime( 7287): 	at com.reactnativestripesdk.CardFormView.setListeners$lambda-18(CardFormView.kt:230)
E/AndroidRuntime( 7287): 	at com.reactnativestripesdk.CardFormView.$r8$lambda$QDgA09d6eOuTuPvpZPP3I-XhHhY(Unknown Source:0)
E/AndroidRuntime( 7287): 	at com.reactnativestripesdk.CardFormView$$ExternalSyntheticLambda6.onInputChanged(Unknown Source:2)
E/AndroidRuntime( 7287): 	at com.stripe.android.view.CardFormView$cardValidTextWatcher$1.afterTextChanged(CardFormView.kt:93)
E/AndroidRuntime( 7287): 	at android.widget.TextView.sendAfterTextChanged(TextView.java:10561)
E/AndroidRuntime( 7287): 	at android.widget.TextView$ChangeWatcher.afterTextChanged(TextView.java:13402)
E/AndroidRuntime( 7287): 	at android.text.SpannableStringBuilder.sendAfterTextChanged(SpannableStringBuilder.java:1277)
E/AndroidRuntime( 7287): 	at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:577)
E/AndroidRuntime( 7287): 	at androidx.emoji2.text.SpannableBuilder.replace(SpannableBuilder.java:315)
E/AndroidRuntime( 7287): 	at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:507)
E/AndroidRuntime( 7287): 	at androidx.emoji2.text.SpannableBuilder.replace(SpannableBuilder.java:305)
E/AndroidRuntime( 7287): 	at androidx.emoji2.text.SpannableBuilder.replace(SpannableBuilder.java:49)
E/AndroidRuntime( 7287): 	at android.text.method.NumberKeyListener.onKeyDown(NumberKeyListener.java:131)
E/AndroidRuntime( 7287): 	at android.widget.TextView.doKeyDown(TextView.java:8440)
E/AndroidRuntime( 7287): 	at android.widget.TextView.onKeyDown(TextView.java:8197)
E/AndroidRuntime( 7287): 	at android.view.KeyEvent.dispatch(KeyEvent.java:2853)
E/AndroidRuntime( 7287): 	at android.view.View.dispatchKeyEvent(View.java:13392)
E/AndroidRuntime( 7287): 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1932)
E/AndroidRuntime( 7287): 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1932)
E/AndroidRuntime( 7287): 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1932)
E/AndroidRuntime( 7287): 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1932)
E/AndroidRuntime( 7287): 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1932)
E/AndroidRuntime( 7287): 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1932)
E/AndroidRuntime( 7287): 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1932)
E/AndroidRuntime( 7287): 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1932)
E/AndroidRuntime( 7287): 	at io.flutter.embedding.android.FlutterView.dispatchKeyEvent(FlutterView.java:916)
E/AndroidRuntime( 7287): 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1932)
E/AndroidRuntime( 7287): 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1932)
E/AndroidRuntime( 7287): 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1932)
E/AndroidRuntime( 7287): 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1932)
E/AndroidRuntime( 7287): 	at com.android.internal.policy.DecorView.superDispatchKeyEvent(DecorView.java:453)
E/AndroidRuntime( 7287): 	at com.android.internal.policy.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1842)
E/AndroidRuntime( 7287): 	at android.app.Activity.dispatchKeyEvent(Activity.java:3966)
E/AndroidRuntime( 7287): 	at androidx.core.app.ComponentActivity.superDispatchKeyEvent(ComponentActivity.java:126)
E/AndroidRuntime( 7287): 	at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:86)
E/AndroidRuntime( 7287): 	at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.java:144)
E/AndroidRuntime( 7287): 	at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:367)
E/AndroidRuntime( 7287): 	at io.flutter.embedding.android.FlutterView.redispatch(FlutterView.java:1112)
E/AndroidRuntime( 7287): 	at io.flutter.embedding.android.KeyboardManager.onUnhandled(KeyboardManager.java:250)
E/AndroidRuntime( 7287): 	at io.flutter.embedding.android.KeyboardManager.access$000(KeyboardManager.java:43)
E/AndroidRuntime( 7287): 	at io.flutter.embedding.android.KeyboardManager$PerEventCallbackBuilder$Callback.onKeyEventHandled(KeyboardManager.java:192)
E/AndroidRuntime( 7287): 	at io.flutter.embedding.android.KeyChannelResponder.lambda$handleEvent$0(KeyChannelResponder.java:51)
E/AndroidRuntime( 7287): 	at io.flutter.embedding.android.KeyChannelResponder$$ExternalSyntheticLambda0.onFrameworkResponse(Unknown Source:2)
E/AndroidRuntime( 7287): 	at io.flutter.embedding.engine.systemchannels.KeyEventChannel.lambda$createReplyHandler$0(KeyEventChannel.java:95)
E/AndroidRuntime( 7287): 	at io.flutter.embedding.engine.systemchannels.KeyEventChannel$$ExternalSyntheticLambda0.reply(Unknown Source:2)
E/AndroidRuntime( 7287): 	at io.flutter.plugin.common.BasicMessageChannel$IncomingReplyHandler.reply(BasicMessageChannel.java:200)
E/AndroidRuntime( 7287): 	at io.flutter.embedding.engine.dart.DartMessenger.handlePlatformMessageResponse(DartMessenger.java:375)
E/AndroidRuntime( 7287): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessageResponse(FlutterJNI.java:1003)
E/AndroidRuntime( 7287): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/AndroidRuntime( 7287): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/AndroidRuntime( 7287): 	at android.os.Looper.loop(Looper.java:174)
E/AndroidRuntime( 7287): 	at android.app.ActivityThread.main(ActivityThread.java:7554)
E/AndroidRuntime( 7287): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 7287): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/AndroidRuntime( 7287): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)
I/Process ( 7287): Sending signal. PID: 7287 SIG: 9
Lost connection to device.
Exited (sigterm)
`

**Comment by mohitmarfatia** [comment]
Hey @jamesblasco, the client needed the payment setup asap, so I went through stripe docs and used stripe api, and dropped the package! Looks like @Naveed44 here has same problem as me, so not closing the issue! Thanks, anyways 
Cheers 🍻

**Comment by remonh87** [comment]
can you check your pubspec.lock file and provide us the stripe_android  entry?  It looks like there is some  old version there . I tried to reproduce it on the example app but no problem there.

@mohitmarfatia  please be aware that your client now needs to be PCI compliant because it is using a custom widget to process card details. The widgets used in this sdk are native stripe widgets and Stripe already handles a lot of PCI compliance and thus you only need to do the minimum level.

**Comment by chunlee-thong** [comment]
If you're using a workaround from this issue #1000, update the `financial-connections` to version 20.15.0.
It works for me with `flutter_stripe: ^7.0.0`
