### ISSUE TITLE
Stripe popup while taping app crash on mm/yyyy 

### ISSUE THREAD

**Issue by rashmisridar** [flutter-stripe/flutter_stripe#1120]
Description : After opening the stripe popup while entering the card payment in the place of mm/yyyy textformfield added  single digit like 2/28 tap multiple time then app crashes.

Below is the error log after crash
Fatal Exception: java.lang.IllegalStateException: OffsetMapping.transformedToOriginal returned invalid mapping: 2 -> -1 is not in range of original text [0, 3]
       at b0.e1.transformedToOriginal(ValidatingOffsetMapping.kt:6)
       at b0.j0$a.i(TextFieldDelegate.kt:2)
       at b0.i$k.invoke-k-4lQ0M(CoreTextField.kt:8)
       at b0.i$k.invoke(CoreTextField.kt:1)
       at b0.p0$a$b$b.invoke-k-4lQ0M(TextFieldPressGestureFilter.kt:1)
       at b0.p0$a$b$b.invoke(TextFieldPressGestureFilter.kt:1)
       at t.c0$e$a$a.invokeSuspend(TapGestureDetector.kt:14)
       at kotlin.coroutines.jvm.internal.a.resumeWith(ContinuationImpl.kt:4)
       at kotlinx.coroutines.f1.d(DispatchedTask.kt:16)
       at kotlinx.coroutines.f1.a(DispatchedTask.kt:9)
       at kotlinx.coroutines.q.o(CancellableContinuationImpl.kt:2)
       at kotlinx.coroutines.q.G(CancellableContinuationImpl.kt:6)
       at kotlinx.coroutines.q.H(CancellableContinuationImpl.kt:1)
       at kotlinx.coroutines.q.resumeWith(CancellableContinuationImpl.kt:1)
       at i1.o0$a.o(SuspendingPointerInputFilter.kt:4)
       at i1.o0.h1(SuspendingPointerInputFilter.kt:11)
       at i1.o0.c1(SuspendingPointerInputFilter.kt:4)
       at n1.c.l(BackwardsCompatNode.kt:2)
       at i1.j.f(HitPathTracker.kt:15)
       at i1.j.f(HitPathTracker.kt:13)
       at i1.j.f(HitPathTracker.kt:13)
       at i1.j.f(HitPathTracker.kt:13)
       at i1.k.f(HitPathTracker.kt:5)
       at i1.f.b(HitPathTracker.kt:8)
       at i1.b0.a(PointerInputEventProcessor.kt:18)
       at androidx.compose.ui.platform.AndroidComposeView.q0(AndroidComposeView.android.kt:14)
       at androidx.compose.ui.platform.AndroidComposeView.T(AndroidComposeView.android.kt:20)
       at androidx.compose.ui.platform.AndroidComposeView.dispatchTouchEvent(AndroidComposeView.android.kt:10)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
       at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:444)
       at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1835)
       at android.app.Activity.dispatchTouchEvent(Activity.java:3465)
       at androidx.appcompat.view.i.dispatchTouchEvent(WindowCallbackWrapper.java:1)
       at io.sentry.android.core.internal.gestures.j.dispatchTouchEvent(WindowCallbackAdapter.java:1)
       at io.sentry.android.core.internal.gestures.h.dispatchTouchEvent(SentryWindowCallback.java:8)
       at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:402)
       at android.view.View.dispatchPointerEvent(View.java:12768)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5287)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5087)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4602)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4655)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4621)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4761)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4629)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4818)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4602)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4655)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4621)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4629)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4602)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7330)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7299)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7260)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7436)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:247)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:326)
       at android.os.Looper.loop(Looper.java:165)
       at android.app.ActivityThread.main(ActivityThread.java:6810)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

**Comment by jamesblasco** [comment]
This looks to be related to the native Android SDK and we do not have control over it. Please if you could create an issue in  https://github.com/stripe/stripe-android. We will make our best to update the dependency as soon as they fix it

**Comment by remonh87** [comment]
closed for now as this is something in the stripe android library and not something we can control
