### ISSUE TITLE
[PAYMENT SHEET] No reaction when invoking presentPaymentSheet method

### ISSUE THREAD

**Issue by mike392** [flutter-stripe/flutter_stripe#115]
Hi, Team,

I am trying to somehow display Payment Sheet. I use this piece of code upon the pressing of a button:

```
void onPressPayCallback(BuildContext context) {
    context.read(clientSecretProvider).when(
        data: (clientSecret) async {
          await Stripe.instance.initPaymentSheet(paymentSheetParameters: SetupPaymentSheetParameters(
            paymentIntentClientSecret: clientSecret!,
            customerId: '<id>',
            // customerEphemeralKeySecret: customerEphemeralKeySecret,
            style: ThemeMode.light,
            applePay: true,
            googlePay: true,
            customFlow: true,
            testEnv: true,
          ));
          await Stripe.instance.presentPaymentSheet(parameters: PresentPaymentSheetParameters(clientSecret: clientSecret));
        },
        loading: () => Center(child: CircularProgressIndicator()),
        error: (error, _) => Center(child: Text(error.toString()))
    );
  }
```
In `clientSecretProvider` i create a PaymentIntent on my SpringBoot backend - and as i debug it is actually provided.

However, when i invoke this... Nothing happens - both on Android (Pixel 3a API 30) and iOS (iPhone 11) simulators.
No error logs as well

Please, advise on how to display the payment sheet or other checkout form option.

My `flutter doctor -v`

```
[✓] Flutter (Channel stable, 2.0.1, on Mac OS X 10.15.7 19H15 darwin-x64, locale en-ES)
    • Flutter version 2.0.1 at 
    • Framework revision c5a4b4029c (3 months ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at 
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 55.1.5
    • Dart plugin version 211.6693.108

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (4 available)
    • sdk gphone x86 arm (mobile) • emulator-5554                        • android-x86    • Android 11 (API 30) (emulator)
    • iPhone 11 (mobile)          • EEDEB002-55D1-4739-834D-327FB55D983A • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-1 (simulator)
    • macOS (desktop)             • macos                                • darwin-x64     • Mac OS X 10.15.7 19H15 darwin-x64
    • Chrome (web)                • chrome                               • web-javascript • Google Chrome 90.0.4430.212

• No issues found!

**Comment by jamesblasco** [comment]
Hello! Right now if you set CustomFlow to true, you have to set confirmPayment: false in presentPaymentSheet.

We have to explain this better or make it more easy to use 👍🏻

**Comment by mike392** [comment]
> Hello! Right now if you set CustomFlow to true, you have to set confirmPayment: false in presentPaymentSheet.
> 
> We have to explain this better or make it more easy to use 👍🏻

Yes, thank you so much for the explanation :) 

And, Guys, please, can you either elaborate a bit more on docs or on some demo videos - because it is a bit hard to work with the lib so far :) However, it raises the entrance barrier which is good in a sense :)

**Comment by jamesblasco** [comment]
Sure we are still working on that part! 🙂

**Comment by mike392** [comment]
To be honest - still - i don't have anything displayed. I have changed for `SetupPaymentSheetParameters` customFlow to true and for `PresentPaymentSheetParameters` confirmPayment to false, and vice versa... 

Still does not display anything

**Comment by mike392** [comment]
No... unfortunately, i don't still see any reaction - neither errors on backend nor in Flutter.

This is my button callback. No reaction when i press the button

```
void onPressPayCallback(BuildContext context) {
    context.read(clientSecretProvider).when(
        data: (clientSecret) async {
          await Stripe.instance.initPaymentSheet(paymentSheetParameters: SetupPaymentSheetParameters(
            paymentIntentClientSecret: clientSecret!,
            customerId: '<customer id>',
            // customerEphemeralKeySecret: customerEphemeralKeySecret,
            style: ThemeMode.light,
            applePay: true,
            googlePay: true,
            customFlow: true,
            testEnv: true,
          ));
          await Stripe.instance.presentPaymentSheet(parameters: PresentPaymentSheetParameters(clientSecret: clientSecret, confirmPayment: false));
        },
        loading: () => Center(child: CircularProgressIndicator()),
        error: (error, _) => Center(child: Text(error.toString()))
    );
  }
```

**Comment by mike392** [comment]
Okay, so i have progressed a bit - In order to be able to see the PaymentSheet you need to enable the Checkout in Stripe Dashboard->Settings-.Payments->Checkout. But still - i have an error saying:
```
W/System  (20292): A resource failed to call release. 
E/flutter (20292): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(Failed, , null, null)
E/flutter (20292): #0      JSONMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:155:7)
E/flutter (20292): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158:18)
E/flutter (20292): <asynchronous suspension>
E/flutter (20292): #2      MethodChannelStripe.presentPaymentSheet (package:stripe_platform_interface/src/method_channel_stripe.dart:181:5)
E/flutter (20292): <asynchronous suspension>
E/flutter (20292): #3      Stripe.presentPaymentSheet (package:flutter_stripe/src/stripe.dart:268:5)
E/flutter (20292): <asynchronous suspension>
E/flutter (20292): 
```

Can you, please, help?
I believe this is something related to the WebView - but i'm not sure - i do not use WebView in my project

**Comment by mike392** [comment]
The behaviour is that - it tries to kind of load - but still goes down disappearing and there is the error appearing above.

**Comment by mike392** [comment]
Okay - the stuff above was for Android Simulator. For iOS simulator i had this:
```
[VERBOSE-2:ui_dart_state.cc(199)] Unhandled Exception: PlatformException(Failed, The operation couldn’t be completed. (Stripe.PaymentSheetError error 0.), null, null)
#0      JSONMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:155:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158:18)
<asynchronous suspension>
#2      MethodChannelStripe.presentPaymentSheet (package:stripe_platform_interface/src/method_channel_stripe.dart:181:5)
<asynchronous suspension>
#3      Stripe.presentPaymentSheet (package:flutter_stripe/src/stripe.dart:268:5)
<asynchronous suspension>
```
Can you, please, hint what to do?

**Comment by mike392** [comment]
Okay, i have progressed a bit. 
When initializing Stripe with publishable key - i added a second row like this:
```
  Stripe.publishableKey = Constants.getPublishableKey();
  await Stripe.instance.applySettings();
```
Otherwise, i guess it was failing to perform the API call. However, now i have the following error:
```
E/MethodChannel#flutter.stripe/payments(21039): Failed to handle method call
E/MethodChannel#flutter.stripe/payments(21039): java.lang.IllegalStateException: FlowController must be successfully initialized using configure() before calling presentPaymentOptions()
E/MethodChannel#flutter.stripe/payments(21039): 	at com.stripe.android.paymentsheet.flowcontroller.DefaultFlowController.presentPaymentOptions(DefaultFlowController.kt:163)
E/MethodChannel#flutter.stripe/payments(21039): 	at com.reactnativestripesdk.PaymentSheetFragment.presentPaymentOptions(PaymentSheetFragment.kt:98)
E/MethodChannel#flutter.stripe/payments(21039): 	at com.reactnativestripesdk.StripeSdkModule.presentPaymentSheet(StripeSdkModule.kt:295)
E/MethodChannel#flutter.stripe/payments(21039): 	at com.flutter.stripe.StripeAndroidPlugin.onMethodCall(StripeAndroidPlugin.kt:96)
E/MethodChannel#flutter.stripe/payments(21039): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#flutter.stripe/payments(21039): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#flutter.stripe/payments(21039): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/MethodChannel#flutter.stripe/payments(21039): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter.stripe/payments(21039): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/MethodChannel#flutter.stripe/payments(21039): 	at android.os.Looper.loop(Looper.java:183)
E/MethodChannel#flutter.stripe/payments(21039): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/MethodChannel#flutter.stripe/payments(21039): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter.stripe/payments(21039): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/MethodChannel#flutter.stripe/payments(21039): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/flutter (21039): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(error, FlowController must be successfully initialized using configure() before calling presentPaymentOptions(), null, java.lang.IllegalStateException: FlowController must be successfully initialized using configure() before calling presentPaymentOptions()
E/flutter (21039): 	at com.stripe.android.paymentsheet.flowcontroller.DefaultFlowController.presentPaymentOptions(DefaultFlowController.kt:163)
E/flutter (21039): 	at com.reactnativestripesdk.PaymentSheetFragment.presentPaymentOptions(PaymentSheetFragment.kt:98)
E/flutter (21039): 	at com.reactnativestripesdk.StripeSdkModule.presentPaymentSheet(StripeSdkModule.kt:295)
E/flutter (21039): 	at com.flutter.stripe.StripeAndroidPlugin.onMethodCall(StripeAndroidPlugin.kt:96)
E/flutter (21039): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/flutter (21039): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/flutter (21039): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/flutter (21039): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (21039): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/flutter (21039): 	at android.os.Looper.loop(Looper.java:183)
E/flutter (21039): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/flutter (21039): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (21039): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/flutter (21039): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/flutter (21039): )
E/flutter (21039): #0      JSONMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:164:7)
E/flutter (21039): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158:18)
E/flutter (21039): <asynchronous suspension>
E/flutter (21039): #2      MethodChannelStripe.presentPaymentSheet (package:stripe_platform_interface/src/method_channel_stripe.dart:181:5)
E/flutter (21039): <asynchronous suspension>
E/flutter (21039): #3      Stripe.presentPaymentSheet (package:flutter_stripe/src/stripe.dart:268:5)
E/flutter (21039): <asynchronous suspension>
E/flutter (21039): 
```

Can you, please, hint me regarding this one?

**Comment by jonasbark** [comment]
Does the example work for you? 
> FlowController must be successfully initialized using configure() before calling presentPaymentOptions 
would indicate that you did not call `initPaymentSheet` before calling `presentPaymentSheet`

Also please provide a minimal reproducible example so we can debug your issues

**Comment by mike392** [comment]
I invoke them like this:

```
Stripe.instance
                            .initPaymentSheet(paymentSheetParameters: SetupPaymentSheetParameters(
                            paymentIntentClientSecret: paymentIntentResponse!.clientSecret!,
                            testEnv: true,
                          customFlow: false
                        )).then((value) =>
                        Stripe.instance.presentPaymentSheet(parameters: PresentPaymentSheetParameters(clientSecret: paymentIntentResponse.clientSecret!, confirmPayment: true)));
```

Unfortunately, cannot provide the complete sample because it involves PaymentIntent creation on backend

But,
I set-up like this:
```
  Stripe.publishableKey = Constants.getPublishableKey();
  await Stripe.instance.applySettings();
```
And then i create payment method like this:
```
Stripe.instance.createPaymentMethod(PaymentMethodParams.card()).then(
            (paymentMethod) async {
              if (paymentMethod.id != null) {
                print('payment method id is ' + paymentMethod.id);
              }
              if (paymentMethod.customerId != null) {
                print('payment customer id is ' + paymentMethod.customerId!);
              }
          PaymentIntentRequest request = PaymentIntentRequest(paymentMethod, getIntegerPrice(context, event.price!), event.currency!);
          context.read(paymentClientProvider).createPaymentIntent(request, token).then((paymentIntentResponse) {
            showConfirmationDialog(context, event, paymentIntentResponse, paymentMethod, token);
          }
          );
        }
    );
```

Here `paymentClientProvider` is my REST Client to the backend.
This all of course i did having entered this:
```
CardField(
                                onCardChanged: (card) {
                                  print(card);
                                },
                              ),
```

I REALLY hope this helps... I'm really blind here - no logs, no error messages... Thank you so much in advance!!! :)

**Comment by mike392** [comment]
> Does the example work for you?
> 
> > FlowController must be successfully initialized using configure() before calling presentPaymentOptions
> 
> would indicate that you did not call `initPaymentSheet` before calling `presentPaymentSheet`
> 
> Also please provide a minimal reproducible example so we can debug your issues

To be honest, i tried different places where i perform initPaymentSheet and presentPaymentSheet - all async functions with wait... But it was still the same... My whole class looked like this (with some bits removed):
```
class EventPaymentDetailsPage extends ConsumerWidget {

  void onPressPayCallback(BuildContext context) {
    Stripe.instance.createPaymentMethod(PaymentMethodParams.card()).then(
            (paymentMethod) async {
              if (paymentMethod.id != null) {
                print('payment method id is ' + paymentMethod.id);
              }
              if (paymentMethod.customerId != null) {
                print('payment customer id is ' + paymentMethod.customerId!);
              }
          PaymentIntentRequest request = PaymentIntentRequest(paymentMethod, 1000, "USD");
          <creating payment intent and retrieving client secret>.then((clientSecret) async {
            await Stripe.instance
                .initPaymentSheet(paymentSheetParameters: SetupPaymentSheetParameters(
                paymentIntentClientSecret: clientSecret,
                testEnv: true,
                customFlow: false
            ));
            showConfirmationDialog(context, clientSecret, paymentMethod);
          }
          );
        }
    );
  }

  void onTapBack(BuildContext context) {
    Navigator.of(context).pop();
  }

  @override
  Widget build(BuildContext context, ScopedReader watch) {
    return  Scaffold(
          resizeToAvoidBottomInset: false,
          body: CustomScrollView(
                      slivers: [
                        SliverList(delegate: SliverChildListDelegate([
                          Container(
                            color: Colors.white70,
                            child: Row(
                              mainAxisAlignment: MainAxisAlignment.spaceBetween,
                              children: [
                                BackButton(
                                  color: Theme.of(context).primaryColorDark,
                                  onPressed: () => onTapBack(context),
                                ),
                                TextLabel("Purchase Visit"),
                                Opacity(
                                  opacity: 0,
                                  child: BackButton(
                                    color: Theme.of(context).cardColor,
                                    onPressed: () {},
                                  ),
                                )
                              ],
                            ),
                          ),
              
                        ])),
                        SliverFillRemaining(child: Column(
                            mainAxisAlignment: MainAxisAlignment.start,
                            mainAxisSize: MainAxisSize.min,
                            children: [
                              CardField(
                                onCardChanged: (card) {
                                  print(card);
                                },
                              ),
                              Padding(
                                padding: EdgeInsets.only(top: baseUnit(1)),
                                child: Row(
                                    mainAxisAlignment: MainAxisAlignment.center,
                                    children: [
                                      Expanded(
                                          child: Button(
                                            text: "Pay ${event.price} ${NumberFormat.simpleCurrency(name: "USD").currencySymbol}",
                                            onPressed: () => onPressPayCallback(context, token, event),
                                            transparent: false,
                                            inverted: true,

                                          ))]),
                              ),
                            ],
                          ),
                        )
                      ],
                    ),
                  ),
                ],
              )
          ),
        ),
        loading: () => Center(child: CircularProgressIndicator()),
        error: (error, _) => Center(child: Text(error.toString()))
    );
  }


  void showConfirmationDialog(BuildContext context, Event event, PaymentIntentResponse? paymentIntentResponse, paymentMethod, String token) {
    showModalBottomSheet(
        isDismissible: false,
        context: context,
        builder: (BuildContext context) {
          return Container(
            child: Column(
                children: [
                  Padding(
                    padding: EdgeInsets.only(top: baseUnit(2), left: baseUnit(2), right: baseUnit(2), bottom: baseUnit(1)),
                    child: TextLabel("Please, confirm the payment"),
                  ),
                  Button(
                      text: "Yes, Confirm",
                      onPressed: () async {
                        await Stripe.instance.presentPaymentSheet(parameters: PresentPaymentSheetParameters(clientSecret: paymentIntentResponse!.clientSecret!, confirmPayment: true));
                      },
                      inverted: true,
                  ),
Button(
                      text: "No, Decline",
                      onPressed: () {
                        if (Navigator.of(context).canPop()){
                          Navigator.of(context).pop();
                        }
                      },
                      inverted: true,
                    ),
              
                ]
            ),
          );
        });
  }
}
```

As you can see - i surely invoke `initPaymentSheet` beforehand and it should be completed by the time `presentPaymentSheet` is invoked.

**Comment by jamesblasco** [comment]
The Payment intent is needed to be created properly from the server. You can not create a payment method `card` from the app beforehand as you don't know yet any information about how the user will be paying. 

Here is the server example we use inside our app:
https://github.com/flutter-stripe/flutter_stripe/blob/b8615d7f3d1e437eb6d4ed0516c0d2a3b0a6da84/example/server/src/index.ts#L472-L505

**Comment by mike392** [comment]
@jamesblasco Thank you so much for your response! Can you, please, correct me if i'm wrong (process-wise)?

So, just let me re-cap what i am doing:
1. Via `createPaymentMethod` i create a Card payment method and send it's ID to the backend.
2. On backend i create a PaymentIntent USING (in Spring Boot using stripe-java 20-52-0 libarary): 
    a. CustomerID or the person/body who is a destination for the paymentIntent. 
    b. I put a Card created payment method ID to the paymentMethod field 
    c. Confirmation method - automatic
    d. Off-session - false
    e. Capture method - manual
    f. Currency and amount - from the request from the app
3. For payment sheet initialization and presenting - i use clientSecret from PaymentIntent created on the backend

Can you, please, tell me what could be wrong here? The point is - how can i create a PaymentIntent if i don't have a paymentMethod id upfront? Sorry for that - i might be really misunderstanding something :) 

Thank you so much in advance!

**Comment by mike392** [comment]
Sorry-sorry - now it's working :) I don't have to do step 1 and in step 2 i shall use paymentMethod of a CUSTOMER (if Customer has any of the payment methods available).

Now it's working :) 

Thank you so much!!! Hope this chat helps someone :)

**Comment by jamesblasco** [comment]
You should remove step 1 from the flow. And also b. You can't create a payment method, as you don't know what payment method will be using the user. That is taken care of by the payment sheet.

To check how to create the correct PaymentIntent for a Java server, check the official docs.
https://stripe.com/docs/payments/accept-a-payment#add-server-endpoint

You should go to Add Server Endpoint, and you can see the code for Java

**Comment by jamesblasco** [comment]
Happy to see that you made it work!

**Comment by ollydixon** [comment]
Can someone tell me what the difference between ``paymentIntentClientSecret`` and ``customerEphemeralKeySecret`` I can't find docs anywhere and there's no description on the params.

**Comment by remonh87** [comment]
@ollydixon 

- `paymentIntentClientSecret` => the secret needed to invoke operations on a payment intent (unique for each payment intent).
- `customerEphermeralKeySecret`  => secret that identifies the customer. You can use it for example to retrieve previously stored cards. (unique for every customer)

**Comment by ollydixon** [comment]
@remonh87 thank you! So the ```customerEphermeralKeySecret``` is the customer id?

**Comment by remonh87** [comment]
@ollydixon no the customerId is customerId :) . The epheralkey is a temporary key to execute API operations related to a specific customer. For more info see: https://stripe.com/docs/mobile/android/basic#set-up-ephemeral-key

**Comment by ollydixon** [comment]
@remonh87 thanks you saved me hours of my life.
