### ISSUE TITLE
[PAYMENT SHEET] Android doesn't show payment sheet when presentPaymentSheet

### ISSUE THREAD

**Issue by mike392** [flutter-stripe/flutter_stripe#1310]
**Describe the bug**
After invoking initPaymentSheet the method presentPaymentSheet throws an exception and doesn't show up. There comes the stacktrace like this:
```
[+1973 ms] E/flutter (22178): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Exception: StripeException(error: LocalizedErrorMessage(code: FailureCode.Failed, localizedMessage: No payment sheet has been initialized yet. You must call `initPaymentSheet` before `presentPaymentSheet`., message: No payment sheet has been initialized yet. You must call `initPaymentSheet` before `presentPaymentSheet`., stripeErrorCode: null, declineCode: null, type: null))
[        ] E/flutter (22178): #0      VisitRequestDescriptionPage.build.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:<source_widget>t:92:47)
[        ] E/flutter (22178): #1      FutureExtensions.onError.onError (dart:async/future.dart:1069:25)
[        ] E/flutter (22178): #2      _RootZone.runBinary (dart:async/zone.dart:1666:54)
[        ] E/flutter (22178): #3      _FutureListener.handleError (dart:async/future_impl.dart:162:22)
[        ] E/flutter (22178): #4      Future._propagateToListeners.handleError (dart:async/future_impl.dart:796:47)
[        ] E/flutter (22178): #5      Future._propagateToListeners (dart:async/future_impl.dart:817:13)
[        ] E/flutter (22178): #6      Future._completeError (dart:async/future_impl.dart:592:5)
[        ] E/flutter (22178): #7      _RootZone.runBinary (dart:async/zone.dart:1666:54)
[        ] E/flutter (22178): #8      _FutureListener.handleError (dart:async/future_impl.dart:162:22)
[        ] E/flutter (22178): #9      Future._propagateToListeners.handleError (dart:async/future_impl.dart:796:47)
[        ] E/flutter (22178): #10     Future._propagateToListeners (dart:async/future_impl.dart:817:13)
[        ] E/flutter (22178): #11     Future._completeError (dart:async/future_impl.dart:592:5)
```

**To Reproduce**
For the button i have the following code:
```
           Button(text: "Pay for ticket",
                                        onPressed: () async {
                                          await ref.read(paymentIntentRestClient).createPaymentIntent(
                                              {
                                                "amount": getEventPriceWithCommission(
                                                    event, request.commissionPercentToCharge ?? 0).toString(),
                                                "currency": event.pricing!.currency!,
                                                "userId": profile!.userId!,
                                                "customerId": profile.paymentInfo.customerId,
                                                "description": "Payment of ${profile.userId} with number ${profile
                                                    .userNumber} for event ${event.id} "
                                                    "to host ${event.host?.userId} with number ${event.host
                                                    ?.userNumber}"
                                              }).then((intent) async {
                                            await Stripe.instance.initPaymentSheet(
                                                paymentSheetParameters: SetupPaymentSheetParameters(
                                                  customFlow: true,
                                                  customerId: profile.paymentInfo.customerId,
                                                  paymentIntentClientSecret: intent!.clientSecret,
                                                  primaryButtonLabel: AppLocalizations.of(context)!.common_button_pay,
                                                  billingDetailsCollectionConfiguration: BillingDetailsCollectionConfiguration(
                                                      name: CollectionMode.never,
                                                      address: AddressCollectionMode.never
                                                  ),
                                                  customerEphemeralKeySecret: intent.customerEphemeralKey,
                                                )).onError((error, stackTrace) {
                                                  print(stackTrace.toString());
                                            });
                                            await Stripe.instance.presentPaymentSheet(options: PaymentSheetPresentOptions()).then((value) async {
                                              print("Payment successful");
                                              PaymentTransaction transaction = buildTransaction(event, request, intent.id, ref.read(paymentCommissionPercentageProvider) ?? 0);
                                              await ref.read(transactionRestProvider).postTransaction(transaction);
                                              await ref.read(visitRequestsRestProvider).toggleVisitRequestStatus(request.id!, { 'orderId': intent.id,
                                                'status': VisitRequestStatus.PAYMENT_SUBMITTED.name });
                                              await ref.read(visitRequestsRestProvider).generateTicketForVisitRequest(request.id!);
                                            })
                                                .onError((error, stackTrace) {
                                              throw Exception(error);
                                            });
                                          });
                                        },
                                        backgroundColor: Theme
                                            .of(context)
                                            .primaryColor,
                                        labelColor: Theme
                                            .of(context)
                                            .cardColor)
```

`ref.read(paymentIntentRestClient).createPaymentIntent` this code requests backend to create a PaymentIntent with the following params (Java):
```
 PaymentIntentCreateParams params = PaymentIntentCreateParams.builder()
                .setCaptureMethod(PaymentIntentCreateParams.CaptureMethod.MANUAL)
                .setPaymentMethodOptions(PaymentIntentCreateParams.PaymentMethodOptions.builder()
                    .setCard(PaymentIntentCreateParams.PaymentMethodOptions.Card.builder()
                        .setRequestThreeDSecure(PaymentIntentCreateParams.PaymentMethodOptions.Card.RequestThreeDSecure.AUTOMATIC)
                        .build()).build())
                .setAmount(amount)
                .setDescription(description)
                .setConfirmationMethod(PaymentIntentCreateParams.ConfirmationMethod.AUTOMATIC)
                .setCurrency(currency)
                .setCustomer(id)
                .build();
```

**Expected behavior**
PaymentSheet should show up on Android. On iOS works like charm.
Please, HELP!

**Additional context**
Flutter doctor -v
```
[✓] Flutter (Channel stable, 3.10.5, on macOS 13.4.1 22F82 darwin-x64, locale en-ES)
    • Flutter version 3.10.5 on channel stable at /Users/mikhailbarsukou/work/apps/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (4 weeks ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/mikhailbarsukou/Library/Android/sdk
    • Platform android-33, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 72.1.4
    • Dart plugin version 223.8214.16

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] VS Code (version 1.80.0)
    • VS Code at /Library/Application Support/JamfAppInstallers/com.microsoft.VSCode/root/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (3 available)
    • 2112123AG (mobile) • 2f50e289 • android-arm64  • Android 13 (API 33)
    • macOS (desktop)    • macos    • darwin-x64     • macOS 13.4.1 22F82 darwin-x64
    • Chrome (web)       • chrome   • web-javascript • Google Chrome 114.0.5735.198

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

**Comment by remonh87** [comment]
Did you follow the instructions mentioned at: https://docs.page/flutter-stripe/flutter_stripe/troubleshooting#the-plugin-is-crashing-with-a-platformexception-on-android-on-ios-it-is-working-fine. ?

**Comment by mike392** [comment]
Yes, unfortunately. I followed all the instructions in the troubleshooting guide but still `No payment sheet has been initialized yet` appears...

**Comment by mike392** [comment]
Is there generally any possibility to throw exceptions if anything fails when doing initPaymentSheet? It does look like it swallows exceptions and nothing could be traced/understood

**Comment by mike392** [comment]
Okay, i found the problem and it's now working. Guys, !PLEASE! :) add to the docs that `merchantDisplayName` parameter of `SetupPaymentSheetParameters`  is mandatory. Without it iOS works but Android doesn't - dunno why, but it is how it is :)
