### ISSUE TITLE
Successful payment on iOS brings error

### ISSUE THREAD

**Issue by michalowskim** [flutter-stripe/flutter_stripe#1342]
**Describe the bug**
After a successful payment on iOS using `presentPaymentSheet` method, error 
`type 'List<dynamic>' is not a subtype of type 'Map<String, dynamic>?'
	#0      MethodChannelStripe.presentPaymentSheet (package:stripe_platform_interface/src/method_channel_stripe.dart:265:37)
	<asynchronous suspension>
	#1      Stripe.presentPaymentSheet (package:flutter_stripe/src/stripe.dart:517:12)
	<asynchronous suspension>` 
occurs

**To Reproduce**
Just make an successful payment on iOS using presentPaymentSheet method.

**Expected behavior**
No error occurs when payment is successful

**Additional context**
iOS sdk on successful payment return empty list as a result. Someone just removed the check if the result coming from `presentPaymentSheet` is a list despite the fact that there was a comment saying that iOS returns empty list on success.

**Comment by jonasbark** [comment]
Duplicate of https://github.com/flutter-stripe/flutter_stripe/issues/1321
