### ISSUE TITLE
Issue while launching payment sheet

### ISSUE THREAD

**Issue by pritamkarmakar** [flutter-stripe/flutter_stripe#1358]
**Describe the bug**
I'm using `9.3.0` version and when try to launch the paymentsheet (` await Stripe.instance.presentPaymentSheet()`) getting below error

```
Background concurrent copying GC freed 11687(1308KB) AllocSpace objects, 183(3660KB) LOS objects, 48% free, 6456KB/12MB, paused 6.220ms total 170.499ms
E/MethodChannel#flutter.stripe/payments( 2489): Failed to handle method call
E/MethodChannel#flutter.stripe/payments( 2489): java.lang.IllegalStateException: FlowController must be successfully initialized using configureWithPaymentIntent(), configureWithSetupIntent() or configureWithIntentConfiguration() before calling presentPaymentOptions().
E/MethodChannel#flutter.stripe/payments( 2489): 	at com.stripe.android.paymentsheet.flowcontroller.DefaultFlowController.presentPaymentOptions(DefaultFlowController.kt:239)
E/MethodChannel#flutter.stripe/payments( 2489): 	at com.reactnativestripesdk.PaymentSheetFragment.present(PaymentSheetFragment.kt:182)
E/MethodChannel#flutter.stripe/payments( 2489): 	at com.reactnativestripesdk.StripeSdkModule.presentPaymentSheet(StripeSdkModule.kt:186)
E/MethodChannel#flutter.stripe/payments( 2489): 	at com.flutter.stripe.StripeAndroidPlugin.onMethodCall(StripeAndroidPlugin.kt:130)
E/MethodChannel#flutter.stripe/payments( 2489): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/MethodChannel#flutter.stripe/payments( 2489): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#flutter.stripe/payments( 2489): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/MethodChannel#flutter.stripe/payments( 2489): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#flutter.stripe/payments( 2489): 	at android.os.Handler.handleCallback(Handler.java:883)
E/MethodChannel#flutter.stripe/payments( 2489): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/MethodChannel#flutter.stripe/payments( 2489): 	at android.os.Looper.loop(Looper.java:214)
E/MethodChannel#flutter.stripe/payments( 2489): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/MethodChannel#flutter.stripe/payments( 2489): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter.stripe/payments( 2489): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/MethodChannel#flutter.stripe/payments( 2489): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**To Reproduce**
This is what I did -

```
                                 // 1. in main.dart did the init
                                Future<void> _initStripePayment() async {
                                  final publishKey = await getStripeApplicationID();
                                  Stripe.publishableKey = publishKey;
                                  await Stripe.instance.applySettings();
                                }

                                // 2. Calling backend service to create the payment intent

                                // 3. in a checkout screen, initialize the payment sheet
                                await Stripe.instance.initPaymentSheet(
                                  paymentSheetParameters:
                                      SetupPaymentSheetParameters(
                                    // Enable custom flow
                                    customFlow: true,
                                    // Main params
                                    merchantDisplayName:
                                        'Flutter Stripe Store Demo',
                                    paymentIntentClientSecret:
                                        value.clientSecret,
                                    // Customer keys
                                    customerEphemeralKeySecret:
                                        value.ephemeralKey,
                                    customerId: value.customerId,
                                    googlePay: PaymentSheetGooglePay(
                                      merchantCountryCode: 'US',
                                      currencyCode: 'USD',
                                      testEnv: true,
                                    ),
                                    style: ThemeMode.dark,
                                  ),
                                );

                                //STEP 4: Display Payment sheet
                                await Stripe.instance.presentPaymentSheet();
```

**Smartphone / tablet**
 - Device: Android emulator
 - OS: Android
 - Package version: `9.3.0`
 - Flutter version 3.3.4

**Additional context**

**Comment by remonh87** [comment]
did you follow the instructions set here: 

https://github.com/flutter-stripe/flutter_stripe#android

**Comment by appeventic** [comment]
@remonh87 thanks for looking into it. Yes, I have followed all those steps. Please see details here https://docs.google.com/document/d/1N4k5DvtCyOiChDIz_bZuJ5LbLMQ2yyvolOocJQxlFlo/edit?usp=sharing

**Comment by pritamkarmakar** [comment]
@remonh87 thanks for looking into it. Yes, I have followed all those steps. Please see details here https://docs.google.com/document/d/1N4k5DvtCyOiChDIz_bZuJ5LbLMQ2yyvolOocJQxlFlo/edit?usp=sharing

**Comment by pritamkarmakar** [comment]
Just found the issue, Stripe publish key was wrong, sorry to bother you.
