### ISSUE TITLE
Problem present payment sheet

### ISSUE THREAD

**Issue by JurojinKun** [flutter-stripe/flutter_stripe#1373]
Good evening,

I have a problem with version 9.3.0 of flutter_stripe when calling the "await Stripe.instance.presentPaymentSheet()" function.

I get this error when the modal opens:

```E/MethodChannel#flutter.stripe/payments( 7448): Failed to handle method call
E/MethodChannel#flutter.stripe/payments( 7448): java.lang.IllegalStateException: FlowController must be successfully initialized using configureWithPaymentIntent(), configureWithSetupIntent() or configureWithIntentConfiguration() before calling confirm().
E/MethodChannel#flutter.stripe/payments( 7448):         at com.stripe.android.paymentsheet.flowcontroller.DefaultFlowController.confirm(DefaultFlowController.kt:269)
E/MethodChannel#flutter.stripe/payments( 7448):         at com.reactnativestripesdk.PaymentSheetFragment.confirmPayment(PaymentSheetFragment.kt:226)
E/MethodChannel#flutter.stripe/payments( 7448):         at com.reactnativestripesdk.StripeSdkModule.confirmPaymentSheetPayment(StripeSdkModule.kt:197)
E/MethodChannel#flutter.stripe/payments( 7448):         at com.flutter.stripe.StripeAndroidPlugin.onMethodCall(StripeAndroidPlugin.kt:134)
E/MethodChannel#flutter.stripe/payments( 7448):         at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/MethodChannel#flutter.stripe/payments( 7448):         at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#flutter.stripe/payments( 7448):         at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/MethodChannel#flutter.stripe/payments( 7448):         at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#flutter.stripe/payments( 7448):         at android.os.Handler.handleCallback(Handler.java:883)
E/MethodChannel#flutter.stripe/payments( 7448):         at android.os.Handler.dispatchMessage(Handler.java:100)
E/MethodChannel#flutter.stripe/payments( 7448):         at android.os.Looper.loop(Looper.java:214)
E/MethodChannel#flutter.stripe/payments( 7448):         at android.app.ActivityThread.main(ActivityThread.java:7356)
E/MethodChannel#flutter.stripe/payments( 7448):         at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter.stripe/payments( 7448):         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/MethodChannel#flutter.stripe/payments( 7448):         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

I'm using the example application from the package in the "Payment sheet" section, "Custom flow" on Android.
The first step works fine, but the second step returns the error shown above.

The first step is:

```
Future<void> initPaymentSheet() async {
    try {
      // 1. create payment intent on the server
      final data = await createTestPaymentSheet(100, 'USD');

      // 2. initialize the payment sheet
      await Stripe.instance.initPaymentSheet(
        paymentSheetParameters: SetupPaymentSheetParameters(
          // Enable custom flow
          customFlow: true,
          // Main params
          merchantDisplayName: 'Flutter Stripe Store Demo',
          paymentIntentClientSecret: data['paymentIntent'],
          // Customer keys
          customerEphemeralKeySecret: data['ephemeralKey'],
          customerId: data['customer'],
          // Extra options
          applePay: PaymentSheetApplePay(
            merchantCountryCode: 'DE',
          ),
          googlePay: PaymentSheetGooglePay(merchantCountryCode: 'DE'),
          style: ThemeMode.light,
        ),
      );
      setState(() {
        step = 1;
      });
    } catch (e) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text('Error: $e')),
      );
      rethrow;
    }
  }
```

The second step is:

```
Future<void> presentPaymentSheet() async {
    try {
      // 3. display the payment sheet.
      await Stripe.instance.presentPaymentSheet();

      setState(() {
        step = 2;
      });

      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text('Payment option selected'),
        ),
      );
    } on Exception catch (e) {
      if (e is StripeException) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Error from Stripe: ${e.error.localizedMessage}'),
          ),
        );
      } else {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Unforeseen error: ${e}'),
          ),
        );
      }
    }
  }
```

Can you tell me if you have the same error and if you have a solution?
Thanks in advance.

**Comment by remonh87** [comment]
If you use custom flow you also need to make sure to confirm the paymentsheet . Can you also test it when setting custom flow to false?
