### ISSUE TITLE
collectBankAccount returns PlatformException

### ISSUE THREAD

**Issue by chilimsv** [flutter-stripe/flutter_stripe#1467]
**Describe the bug**
Calling collectBankAccount on both iOS and Android returns `PlatformException(Invalid Params, , , null)`

**To Reproduce**
Call this function 
```
 const billingDetails = BillingDetails(
        name: 'Flutter Stipe',
        email: 'email@stripe.com',
        phone: '+48888000888',
        address: Address(
          city: 'Houston',
          country: 'US',
          line1: '1459  Circle Drive',
          line2: 'S',
          state: 'Texas',
          postalCode: '77063',
        ),
      );
      await Stripe.instance.collectBankAccount(
        isPaymentIntent: true,
        clientSecret: paymentInfo.clientSecret,
        params: const CollectBankAccountParams(
          paymentMethodType: PaymentMethodType.USBankAccount,
          billingDetails: billingDetails,
        ),
      );
```
This is returned:

```
[   +1 ms] flutter: PlatformException(Invalid Params, , , null)
[        ] flutter: 
           #0      JSONMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:171:7)
           #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310:18)
           <asynchronous suspension>
           #2      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:510:43)
           <asynchronous suspension>
           #3      MethodChannelStripe.collectBankAccount (package:stripe_platform_interface/src/method_channel_stripe.dart:429:20)
           <asynchronous suspension>
           #4      Stripe.collectBankAccount (package:flutter_stripe/src/stripe.dart:583:12)
           <asynchronous suspension>
```

**Expected behavior**
I expect a modal to show up to collect bank details after calling this method with required parameters

Package version: flutter_stripe: 9.5.0+1
Flutter version: stable, 3.13.0

**Additional context**
Is this the wrong usage or a bug? Every parameter is filled

**Comment by xkxeeshankhan** [comment]
@chilimsv any update on the above issue?

**Comment by chilimsv** [comment]
> Hey @chilimsv any update on the above issue?

No luck. Decided to collect the bank details on our client side as a workaround

**Comment by lukatommy** [comment]
Hey, any update on this?  collectBankAccount still doesn't work.

I've found 2 problems:
1. Flutter plugin send 
`'isPaymentIntent':isPaymentIntent` and ios side use wrong key
`let isPaymentIntent = arguments["intentType"] as? Bool,`

2. Flutter plugin send as params `CollectBankAccountParams` parsed to json and both ios and android side try to extract this by `paymentMethodData` which is not in that model.

What with this draft PR?

**Comment by forwardcodetechstudio** [comment]
For now you can use our fork and make this work:

https://github.com/forwardcodetechstudio/flutter_stripe

```
dependency_overrides:
  flutter_stripe:
      git:
        url: https://github.com/forwardcodetechstudio/flutter_stripe
        path: packages/stripe
        
  stripe_platform_interface:
    git:
      url: https://github.com/forwardcodetechstudio/flutter_stripe
      path: packages/stripe_platform_interface
```

**Comment by remonh87** [comment]
this is fixed in the latest version of flutter stripe

**Comment by remonh87** [comment]
also @forwardcodetechstudio  instead of promoting your own fork I would like to invite you to create a pr in our repo if things are still missing and I will make sure we integrate it

**Comment by Adefizzy** [comment]
@remonh87 this issue still persist.

**Comment by forwardcodetechstudio** [comment]
@Adefizzy You can use my fork from this comment.

https://github.com/flutter-stripe/flutter_stripe/issues/1467#issuecomment-2829716886
