### ISSUE TITLE
CardFieldView create crash when user enter data in card field and simply back press 

### ISSUE THREAD

**Issue by Tamimii** [flutter-stripe/flutter_stripe#1554]
**Describe the bug**

**To Reproduce**
1. Entering number 123-456-789 into the cardfield.
2. Tapping the confirm button.
3. Observe a failure with exception (including the part of the stack trace, belonging to this package) …

**Expected behavior**
FATAL EXCEPTION: main
                                                                                                    Process: com.example.myapp, PID: 17908
                                                                                                    java.lang.IllegalStateException: Cannot locate windowRecomposer; View androidx.compose.ui.platform.ComposeView{c41ee19 V.E...... ......I. 0,0-72,37 #7f080141 app:id/icon aid=1073741832} is not attached to a window
                                                                                                    	at androidx.compose.ui.platform.WindowRecomposer_androidKt.getWindowRecomposer(WindowRecomposer.android.kt:295)
                                                                                                    	at androidx.compose.ui.platform.AbstractComposeView.resolveParentCompositionContext(ComposeView.android.kt:244)
                                                                                                    	at androidx.compose.ui.platform.AbstractComposeView.ensureCompositionCreated(ComposeView.android.kt:251)
                                                                                                    	at androidx.compose.ui.platform.AbstractComposeView.onMeasure(ComposeView.android.kt:288)
                                                                                                    	at android.view.View.measure(View.java:27131)
                                                                                                    	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7951)
                                                                                                    	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                                                    	at android.view.View.measure(View.java:27131)
                                                                                                    	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7951)
                                                                                                    	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
                                                                                                    	at android.widget.LinearLayout.measureHorizontal(LinearLayout.java:1204)
                                                                                                    	at android.widget.LinearLayout.onMeasure(LinearLayout.java:723)
                                                                                                    	at android.view.View.measure(View.java:27131)
                                                                                                    	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7951)
                                                                                                    	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                                                    	at android.view.View.measure(View.java:27131)
                                                                                                    	at com.reactnativestripesdk.CardFieldView.mLayoutRunnable$lambda$27(CardFieldView.kt:377)
                                                                                                    	at com.reactnativestripesdk.CardFieldView.$r8$lambda$tO4Ku94GLM16x8NhrR7Up5q0VFs(Unknown Source:0)
                                                                                                    	at com.reactnativestripesdk.CardFieldView$$ExternalSyntheticLambda2.run(Unknown Source:2)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loop(Looper.java:246)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8625)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
**Smartphone / tablet**
 - Device: [e.g. iPhone X]
 - OS: [e.g. iOS 13, Android 10]
 - Package version: [e.g. 1.0.0]
 - Flutter version [e.g. 2.0.0.]

**Additional context**

**Comment by remonh87** [comment]
please use the template for filing issues. Include the device, flutter version, Also did you try to reproduce this on the example app?

**Comment by Tamimii** [comment]
Sorry. Now I have updated issue with provided template and enters complete details. Please help me out to fix this issue.

**Comment by angelo-hub** [comment]
+1 seeing this in the react-native logs as well seems like an android sdk bug
