### ISSUE TITLE
CardFieldView create crash when user enter data in card field and simply back press means Exit app

### ISSUE THREAD

**Issue by Tamimii** [flutter-stripe/flutter_stripe#1556]
**Describe the bug**
When user enter card details in card field and simply back press CardFiled throw exception. I'm using strip implementation to get payment token and my rest implantation is on server. When I use already saved card payment processed success but when use cardfiled exception thrown by CardFiled.

**To Reproduce**
1. Entering number 123-456-789 into the cardfield.
2. Tapping the confirm button.
3. Observe a failure with exception (including the part of the stack trace, belonging to this package) …

**Expected behavior**
When back press means flutter app exit then exception is thrown 

```
 FATAL EXCEPTION: main
 
Process: com.wellyx.uk, PID: 17547
                                                                                                    

java.lang.IllegalStateException: Cannot locate windowRecomposer; View androidx.compose.ui.platform.ComposeView{7c4678f V.E...... ......I. 0,0-72,37 #7f0a03ca app:id/icon aid=1073741837} is not attached to a window
                                                                                                    	at androidx.compose.ui.platform.WindowRecomposer_androidKt.getWindowRecomposer(WindowRecomposer.android.kt:295)
                                                                                                    	at androidx.compose.ui.platform.AbstractComposeView.resolveParentCompositionContext(ComposeView.android.kt:244)
                                                                                                    	at androidx.compose.ui.platform.AbstractComposeView.ensureCompositionCreated(ComposeView.android.kt:251)
                                                                                                    	at androidx.compose.ui.platform.AbstractComposeView.onMeasure(ComposeView.android.kt:288)
                                                                                                    	at android.view.View.measure(View.java:27131)
                                                                                                    	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7951)
                                                                                                    	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                                                    	at android.view.View.measure(View.java:27131)
                                                                                                    	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7951)
                                                                                                    	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
                                                                                                    	at android.widget.LinearLayout.measureHorizontal(LinearLayout.java:1204)
                                                                                                    	at android.widget.LinearLayout.onMeasure(LinearLayout.java:723)
                                                                                                    	at android.view.View.measure(View.java:27131)
                                                                                                    	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7951)
                                                                                                    	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                                                    	at android.view.View.measure(View.java:27131)
                                                                                                    	at com.reactnativestripesdk.CardFieldView.mLayoutRunnable$lambda$27(CardFieldView.kt:377)
                                                                                                    	at com.reactnativestripesdk.CardFieldView.$r8$lambda$tO4Ku94GLM16x8NhrR7Up5q0VFs(Unknown Source:0)
                                                                                                    	at com.reactnativestripesdk.CardFieldView$$ExternalSyntheticLambda2.run(Unknown Source:2)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loop(Looper.java:246)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8625)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

```
**Smartphone / tablet**
 - Device: [e.g. iPhone X]
 - OS: [e.g. iOS 13, Android 10]
 - Package version: [e.g. 1.0.0]
 - Flutter version [e.g. 2.0.0.]

**Additional context**
Actually I'm Using flutter module for stripe payment in native android app when move to flutter module and fills new card information and get token, process payment and and call finishAfinity() exception was thrown by cardField even in flutter module when user enters new card details exit app without processing payment exception is thrown

**Comment by remonh87** [comment]
cannot reproduce it did you follow the instructions stated [here](https://github.com/flutter-stripe/flutter_stripe?tab=readme-ov-file#android) .

**Comment by Tamimii** [comment]
I'm sharing my code please create new flutter project using latest flutter sdk and just past my code and you will see the exception thrown. 
```

import 'package:flutter/material.dart';
import 'package:flutter_stripe/flutter_stripe.dart';
/**
 * Copyright (c) 2023, Soft Steer & Co (SMC) Private Limited
 * All rights reserved.
 *
 * Author: M. JAMAL
 * Date: 18/12/2023
 */

class ThemeCardExample extends StatefulWidget {
  @override
  _ThemeCardExampleState createState() => _ThemeCardExampleState();
}

class _ThemeCardExampleState extends State<ThemeCardExample> {
  late String _index = 'Filled Green';
  bool postalCodeEnabled = false;

  Map<String, ThemeData> get themes => {
    'Default': ThemeData.light().copyWith(),
    'Filled Green': ThemeData(
      primaryColor: Colors.green,
      colorScheme: ColorScheme.light(
        primary: Colors.green,
        secondary: Colors.green,
        error: Colors.red,
      ),
      inputDecorationTheme: InputDecorationTheme(
        filled: true,
      ),
    ),
    'Outlined': ThemeData(
      inputDecorationTheme: InputDecorationTheme(
        contentPadding: EdgeInsets.all(12),
        border: OutlineInputBorder(),
      ),
    ),
    'Filled with label': ThemeData.light().copyWith(
      inputDecorationTheme: InputDecorationTheme(
        filled: true,
        floatingLabelBehavior: FloatingLabelBehavior.always,
        contentPadding: EdgeInsets.all(12),
      ),
    ),
    'Dark': ThemeData(
      brightness: Brightness.dark,
      colorScheme: ColorScheme.dark(secondary: Colors.purpleAccent),
    ),
    'Dark filled': ThemeData(
      brightness: Brightness.dark,
      colorScheme: ColorScheme.dark(secondary: Colors.blue[200]!),
      inputDecorationTheme: InputDecorationTheme(
        focusColor: Colors.red,
        filled: true,
        floatingLabelBehavior: FloatingLabelBehavior.always,
        contentPadding: EdgeInsets.symmetric(vertical: 16, horizontal: 12),
        hintStyle: TextStyle(color: Colors.blue[100]),
        border: UnderlineInputBorder(
          borderSide: BorderSide(color: Colors.blue[100]!),
        ),
        isCollapsed: true,
      ),
    ),
  };
  @override
  Widget build(BuildContext context) {
    final theme = themes[_index]!;

    return Scaffold(
      appBar: AppBar(),
      body: Column(
        children: [
          Theme(
            data: theme,
            child: Container(
              height: 150,
              alignment: Alignment.center,
              padding: EdgeInsets.symmetric(vertical: 20, horizontal: 20),
              color: theme.scaffoldBackgroundColor,
              child: CardField(
                autofocus: true,
                enablePostalCode: postalCodeEnabled,

                onCardChanged: (_) {},
                decoration: InputDecoration(
                  labelText: theme.inputDecorationTheme.floatingLabelBehavior ==
                      FloatingLabelBehavior.always
                      ? 'Card Field'
                      : null,
                ),
              ),
            ),
          ),
          Divider(height: 1),
          Expanded(
            child: Container(
              color: Colors.grey[100],
              child: ListView(
                children: [
                  SizedBox(height: 20),
                  ...ListTile.divideTiles(context: context, tiles: [
                    SwitchListTile.adaptive(
                      title: Text('Show postal code field'),
                      value: postalCodeEnabled,
                      onChanged: (v) => setState(() => postalCodeEnabled = v),
                    ),
                    for (final theme in themes.entries)
                      Theme(
                        data: theme.value,
                        child: Container(
                          color: theme.value.scaffoldBackgroundColor,
                          child: ListTile(
                            leading: Icon(
                                theme.key == _index
                                    ? Icons.check_circle
                                    : Icons.circle,
                                color: theme.value.colorScheme.secondary),
                            title: Text(
                              theme.key,
                              style: TextStyle(
                                  color: theme.value.colorScheme.secondary),
                            ),
                            onTap: () {
                              setState(() {
                                _index = theme.key;
                              });
                            },
                          ),
                        ),
                      ),
                  ])
                ],
              ),
            ),
          ),
        ],
      ),
    );
  }
}

```
**main.dart**
```

import 'dart:async';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_stripe/flutter_stripe.dart';
import 'package:provider/provider.dart';
import 'package:untitled/theme_card_example.dart';
import 'package:flutter_easyloading/flutter_easyloading.dart';

import 'MyViewModel.dart';


Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  Stripe.publishableKey = 'pk_test_51H5Wg5BOfeg2MzHlW0cdD0d6HZU2YrKWjSLd7QuoVVj7fOQHn5fyswPWzApz8eVbWCSvMp1MVAJ3fg2rRCNDBOHZ00mUDwzqTZ';
  Stripe.merchantIdentifier = 'merchant.flutter.stripe.test';
  Stripe.urlScheme = 'flutterstripe';
  await Stripe.instance.applySettings();
  runApp(const MyApp());
  configLoading();
}

void configLoading() {
  EasyLoading.instance
    ..indicatorType = EasyLoadingIndicatorType.ring
    ..loadingStyle = EasyLoadingStyle.light
    ..backgroundColor = Colors.black.withOpacity(0.0)
    ..indicatorColor = Colors.blue
    ..textColor = Colors.black.withOpacity(0.0)
    ..userInteractions = true;

}

class MyApp extends StatefulWidget {

  const MyApp({Key? key}) : super(key: key);

  @override
  State<MyApp> createState() => MyAppState();
}

class MyAppState extends State<MyApp> {

  final MyViewModel myViewModel = MyViewModel();
  MethodChannel channel = MethodChannel('test');

  @override
  void initState() {
    super.initState();


  }


  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primaryColor: Color(0xff0b486b),
        scaffoldBackgroundColor: const Color(0xFFEFEFEF),
        tabBarTheme: const TabBarTheme(
            labelColor: Colors.white,
            unselectedLabelColor: Colors.white70,
            labelStyle: TextStyle(color: Colors.pink), // color for text
            indicator: UnderlineTabIndicator(
              // color for indicator (underline)
                borderSide: BorderSide(color: Colors.white))),
        textTheme: TextTheme(
          bodyText1: TextStyle(fontSize: 16.0), // set the default text size
        ),
      ),
      home: ChangeNotifierProvider.value(
        value: myViewModel,
        child: ThemeCardExample(),
      ),
      builder: EasyLoading.init(),
    );
  }


  /*@override
  void dispose() {
    // Dispose of the channel when the widget is disposed
    CommunicationManager()
        .platformChannel.setMethodCallHandler(null); // Set handler to null
    super.dispose();
  }*/
}

```

**MyViewModel**
```

import 'package:flutter/material.dart';

class MyViewModel extends ChangeNotifier {
  // Singleton instance
  static final MyViewModel _instance = MyViewModel._internal();


  // Private constructor for singleton
  MyViewModel._internal();

  // Factory method to access the singleton instance
  factory MyViewModel() => _instance;

  String? _points;
  String? get points => _points;
  set points(String? point){
    _points= point;
    notifyListeners();
  }
  String? _expiryDate;
  String? get expiryDate => _expiryDate;
  set expiryDate(String? exp){
    _expiryDate = exp;
    notifyListeners();
  }
  double? _totalBalance;
  double? get totalBalance=> _totalBalance;
  set totalBalance(double? total){
    _totalBalance = total;
    notifyListeners();
  }
}

```
