### ISSUE TITLE
Type cast fails on Customer Sheet cancel

### ISSUE THREAD

**Issue by ovchars2** [flutter-stripe/flutter_stripe#1721]
**Describe the bug**
When a Customer Sheet is closed, a type cast error is thrown instead of StripeException

**To Reproduce**
1. Open CustomerSheetScreen
2. Init Customer Sheet
3. Present Customer Sheet
4. Close Customer Sheet by tapping above the sheet or using close button in the top right corner

**Expected behavior**
StripeException with FailureCode.Canceled is thrown

**Smartphone / tablet**
 - Device: Pixel 3
 - OS: Android 12
 - Package version: `main` branch
 - Flutter version: 3.19.3

**Additional context**
Logs:
```
W/ActivityResultRegistry(27246): Dropping pending result for request CustomerSheet: ActivityResult{resultCode=RESULT_OK, data=Intent { (has extras) }}
D/StripeReactNative(27246): com.stripe.android.customersheet.InternalCustomerSheetResult$Canceled cannot be cast to com.stripe.android.view.AddPaymentMethodActivityStarter$Result
[log] type 'String' is not a subtype of type 'Map<String, dynamic>' in type cast
      type 'String' is not a subtype of type 'Map<String, dynamic>' in type cast
      #0      _$$StripeErrorGenericImplFromJson (package:stripe_platform_interface/src/models/errors.g.dart:13:40)
      #1      new _$StripeErrorGenericImpl.fromJson (package:stripe_platform_interface/src/models/errors.freezed.dart:123:7)
      #2      _$StripeErrorFromJson (package:stripe_platform_interface/src/models/errors.freezed.dart:18:10)
      #3      new StripeError.fromJson (package:stripe_platform_interface/src/models/errors.dart:26:7)
      #4      _$$CustomerSheetResultImplFromJson (package:stripe_platform_interface/src/models/customer_sheet.g.dart:131:13)
      #5      new _$CustomerSheetResultImpl.fromJson (package:stripe_platform_interface/src/models/customer_sheet.freezed.dart:1024:7)
      #6      _$CustomerSheetResultFromJson (package:stripe_platform_interface/src/models/customer_sheet.freezed.dart:855:31)
      #7      new CustomerSheetResult.fromJson (package:stripe_platform_interface/src/models/customer_sheet.dart:100:7)
      #8      MethodChannelStripe._parseCustomerSheetResult (package:stripe_platform_interface/src/method_channel_stripe.dart:358:36)
      #9      MethodChannelStripe.presentCustomerSheet (package:stripe_platform_interface/src/method_channel_stripe.dart:278:12)
      <asynchronous suspension>
      #10     _CustomerSheetScreenState.confirmCustomerSheet (package:stripe_example/screens/customer_sheet/customer_sheet_screen.dart:119:22)
      <asynchronous suspension>
      #11     _LoadingButtonState._loadFuture (package:stripe_example/widgets/loading_button.dart:50:7)
      <asynchronous suspension>
```

**Comment by Flucadetena** [comment]
This also happens on IOS.

**Comment by Flucadetena** [comment]
I created a pull request to fix this issue. Hopefully it will get merged soon ;)
I'll create a branch in my fork to use this fix and another a fixed in the meantime. Fill free to use it @ovchars2

**Comment by Flucadetena** [comment]
Hi @phawadshah I'm sorry but I'm still using my fork to avoid this issue, I can not tell you more than to use it or check out what I did and see if it helps :)

**Comment by phawadshah** [comment]
@Flucadetena I did use your fork but it did not work. I think you misread my issue. 

1. Closing paymentSheet 
    It throws the expected exception of cancelled.
    

2. My issue is when Confirming a payment via card, and Payment intent status is "requires_action" and you close/cancel the process. You can look this in the photo attached.

I am expecting failureCode.cancelled and it throws failed, since it was cancelled by the user.

![Simulator Screenshot - iPhone 16 Pro Max - 2024-12-05 at 09 54 23](https://github.com/user-attachments/assets/61f9c27a-778d-47d1-ab38-e62365a543dc)

**Comment by remonh87** [comment]
This issue is outdated and customersheet works fully now. IF there are still issues  please create a new one with updated details.
