### ISSUE TITLE
Payment sheet crashes on Android, when tapping delete button

### ISSUE THREAD

**Issue by Andrea951112** [flutter-stripe/flutter_stripe#1735]
**Describe the bug**
When writing the card number if you tap the delete button the entire app crash.

**To Reproduce**
1. open the payment sheet
2. Entering number into the cardfield.
3. Tapping the delete button.

**Smartphone / tablet**
 - OS: Android 12,13,14
 - Package version: 10.1.1
 - Flutter version 3.16.6

**Additional context**
java.lang.NoSuchMethodError: No virtual method getEmojiStart(Ljava/lang/CharSequence;I)I in class Landroidx/emoji2/text/EmojiCompat; or its super classes (declaration of 'androidx.emoji2.text.EmojiCompat'
                                                                                                    	at androidx.compose.foundation.text.StringHelpers_androidKt.findPrecedingBreak(StringHelpers.android.kt:24)
                                                                                                    	at androidx.compose.foundation.text.selection.BaseTextPreparedSelection.getPrecedingCharacterIndex(TextPreparedSelection.kt:150)
                                                                                                    	at androidx.compose.foundation.text.TextFieldKeyInput$process$2$3.invoke(TextFieldKeyInput.kt:131)
                                                                                                    	at androidx.compose.foundation.text.TextFieldKeyInput$process$2$3.invoke(TextFieldKeyInput.kt:129)
                                                                                                    	at androidx.compose.foundation.text.selection.TextFieldPreparedSelection.deleteIfSelectedOr(TextPreparedSelection.kt:397)
                                                                                                    	at androidx.compose.foundation.text.TextFieldKeyInput$process$2.invoke(TextFieldKeyInput.kt:129)
                                                                                                    	at androidx.compose.foundation.text.TextFieldKeyInput$process$2.invoke(TextFieldKeyInput.kt:106)
                                                                                                    	at androidx.compose.foundation.text.TextFieldKeyInput.commandExecutionContext(TextFieldKeyInput.kt:226)
                                                                                                    	at androidx.compose.foundation.text.TextFieldKeyInput.process-ZmokQxo(TextFieldKeyInput.kt:106)
                                                                                                    	at androidx.compose.foundation.text.TextFieldKeyInputKt$textFieldKeyInput$2$1.invoke-ZmokQxo(TextFieldKeyInput.kt:261)
                                                                                                    	at androidx.compose.foundation.text.TextFieldKeyInputKt$textFieldKeyInput$2$1.invoke(TextFieldKeyInput.kt:261)
                                                                                                    	at androidx.compose.ui.input.key.KeyInputNode.onKeyEvent-ZmokQxo(KeyInputModifier.kt:80)
                                                                                                    	at androidx.compose.ui.focus.FocusOwnerImpl.dispatchKeyEvent-ZmokQxo(FocusOwnerImpl.kt:193)
                                                                                                    	at androidx.compose.ui.platform.AndroidComposeView.dispatchKeyEvent(AndroidComposeView.android.kt:647)
                                                                                                    	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1971)
                                                                                                    	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1971)
                                                                                                    	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1971)
                                                                                                    	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1971)
                                                                                                    	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1971)
                                                                                                    	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1971)
                                                                                                    	at com.android.internal.policy.DecorView.superDispatchKeyEvent(DecorView.java:560)
                                                                                                    	at com.android.internal.policy.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1885)
                                                                                                    	at android.app.Activity.dispatchKeyEvent(Activity.java:4234)
                                                                                                    	at androidx.core.app.ComponentActivity.superDispatchKeyEvent(ComponentActivity.java:126)
                                                                                                    	at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:86)
                                                                                                    	at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.java:144)
                                                                                                    	at androidx.appcompat.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:604)
                                                                                                    	at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:60)
                                                                                                    	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:3413)
                                                                                                    	at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:436)
                                                                                                    	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:6594)
                                                                                                    	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6441)
                                                                                                    	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5901)
                                                                                                    	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5958)
                                                                                                    	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5924)
                                                                                                    	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6089)
                                                                                                    	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5932)
                                                                                                    	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6146)
                                                                                                    	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5905)
                                                                                                    	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5958)
                                                                                                    	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5924)

**Comment by aco01-fl** [comment]
Any update on this issue please?
This is a critical one preventing to use this version.

**Comment by remonh87** [comment]
@jonasbark  this is already fixed correct?

**Comment by jonasbark** [comment]
This is a dependency issue, not caused by the plugin. Likely another plugin overrides the dependencies, as seen in all the other issues:
https://github.com/flutter-stripe/flutter_stripe/issues?q=getEmojiStart

**Comment by Andrea951112** [comment]
@jonasbark what dependencies do i need to check?

**Comment by jonasbark** [comment]
Any that may use the emoji libraries in question. 
https://www.google.com/search?q=gradle+list+dependencies
