### ISSUE TITLE
[Exception] when closing customer sheet (Customer Sheet Result deserialization)

### ISSUE THREAD

**Issue by angelorodem** [flutter-stripe/flutter_stripe#1854]
**Describe the bug**
When getting error from stripe, StripeError<dynamic>.fromJson( returns an error
type 'String' is not a subtype of type 'Map<String, dynamic>' in type cast

the code i use is this
```dart
Future<void> confirmCustomerSheet() async {
    try {
      // 3. display the customer sheet.
      final result = await Stripe.instance.presentCustomerSheet();
[...]
```

in this code 

```dart
_$CustomerSheetResultImpl _$$CustomerSheetResultImplFromJson(
        Map<String, dynamic> json) =>
    _$CustomerSheetResultImpl(
      paymentOption: json['paymentOption'] == null
          ? null
          : PaymentSheetPaymentOption.fromJson(
              json['paymentOption'] as Map<String, dynamic>),
      paymentMethod: json['paymentMethod'] == null
          ? null
          : PaymentMethod.fromJson(
              json['paymentMethod'] as Map<String, dynamic>),
      error: json['error'] == null
          ? null
          : StripeError<dynamic>.fromJson( // ------- here
              json['error'] as Map<String, dynamic>),
    );
```

strangely on the debugger the field seems to be a map
![image](https://github.com/user-attachments/assets/1fb912a7-bf3e-4e77-a1a8-2913c45dd109)
but the code still except with this message:

```
[log] type 'String' is not a subtype of type 'Map<String, dynamic>' in type cast
[log] _TypeError (type 'String' is not a subtype of type 'Map<String, dynamic>' in type cast)
[log] #0      _$$StripeErrorGenericImplFromJson (package:stripe_platform_interface/src/models/errors.g.dart:13:40)
      #1      new _$StripeErrorGenericImpl.fromJson (package:stripe_platform_interface/src/models/errors.freezed.dart:123:7)
      #2      _$StripeErrorFromJson (package:stripe_platform_interface/src/models/errors.freezed.dart:18:10)
      #3      new StripeError.fromJson (package:stripe_platform_interface/src/models/errors.dart:26:7)
      #4      _$$CustomerSheetResultImplFromJson (package:stripe_platform_interface/src/models/customer_sheet.g.dart:135:13)
      #5      new _$CustomerSheetResultImpl.fromJson (package:stripe_platform_interface/src/models/customer_sheet.freezed.dart:1060:7)
      #6      _$CustomerSheetResultFromJson (package:stripe_platform_interface/src/models/customer_sheet.freezed.dart:891:31)
      #7      new CustomerSheetResult.fromJson (package:stripe_platform_interface/src/models/customer_sheet.dart:105:7)
      #8      MethodChannelStripe._parseCustomerSheetResult (package:stripe_platform_interface/src/method_channel_stripe.dart:358:36)
      #9      MethodChannelStripe.presentCustomerSheet (package:stripe_platform_interface/src/method_channel_stripe.dart:278:12)
      <asynchronous suspension>
      #10     _CustomerSheetScreenState.confirmCustomerSheet (package:charge_app/pages/payment_page.dart:132:22)
      <asynchronous suspension>
      #11     _LoadingButtonState._loadFuture (package:charge_app/loading_button.dart:50:7)
      <asynchronous suspension>
```

**To Reproduce**
1. Create customer sheet
2. Create payment method
3. close
4. open customer sheet 
5. click on the X button.
6. the error field fails to be converted to map

**Expected behavior**
should not except

this seems to be because error field needs to be decoded before?

**Comment by remonh87** [comment]
![Simulator Screenshot - iPhone 15 - 2024-07-17 at 20 26 21](https://github.com/user-attachments/assets/f4e22e58-30ea-4e5a-acf2-8f233c2c93f0)

I cannot reproduce it on the example app what is the version that you are using?

**Comment by alexodus** [comment]
I've the same problem. I used the last example code, inserted in my app.

**Comment by gaea-vimal** [comment]
Not sure why this issue is closed. I'm still getting the same error. `flutter_stripe: ^11.5.0`

Error

```
I/flutter ( 9466): Error in presentCustomerSheet: type 'String' is not a subtype of type 'Map<String, dynamic>' in type cast
E/flutter ( 9466): [ERROR:flutter/runtime/dart_vm_initializer.cc(40)] Unhandled Exception: type 'String' is not a subtype of type 'Map<String, dynamic>' in type cast
E/flutter ( 9466): #0      _$$StripeErrorGenericImplFromJson (package:stripe_platform_interface/src/models/errors.g.dart:13:40)
```

The above error happens when user clicked outside the widget or clicked (x) button. Any help without forking the code?
