### ISSUE TITLE
Error On the Package

### ISSUE THREAD

**Issue by Erchil66** [flutter-stripe/flutter_stripe#1938]
Error logs, when using stripe payment on android

```
W/ActivityResultRegistry(28539): Dropping pending result for request fragment_e586aea1-e464-414c-ba58-a2b697621250_rq#0: ActivityResult{resultCode=RESULT_OK, data=Intent { (has extras) }}
E/flutter (28539): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: StripeException(error: LocalizedErrorMessage(code: FailureCode.Failed, localizedMessage: Missing required param: payment_method_data[card][number]., message: Missing required param: payment_method_data[card][number]., stripeErrorCode: parameter_missing, declineCode: null, type: invalid_request_error))
E/flutter (28539): #0      ResultParser.parse (package:stripe_platform_interface/src/result_parser.dart:16:7)
E/flutter (28539): #1      MethodChannelStripe.confirmPayment (package:stripe_platform_interface/src/method_channel_stripe.dart:109:10)
```

When calling confirmpaymentsheet,confirmpayment. It induces this error.

**Comment by jonasbark** [comment]
You'll have to provide more information than that.
What exactly did you / the user do? What are you using? Payment Sheet?
