### ISSUE TITLE
Stripe and Jitsimeet not working together in flutter

### ISSUE THREAD

**Issue by subhra9326** [flutter-stripe/flutter_stripe#197]
stripe and Jitsi meet not working together with the latest version
my version is
flutter_stripe: ^1.0.2
  jitsi_meet: ^4.0.0
, can anyone please tell me the reason why it's happening and what is the solution for that.

**Comment by wilpar** [comment]
error logs please...

**Comment by subhra9326** [comment]
[+12606 ms] D/JITSI_MEET_PLUGIN(15785): JitsiMeetEventStreamHandler.onListen
[   +2 ms] D/JITSI_MEET_PLUGIN(15785): JitsiMeetEventStreamHandler.onCancel
[   +1 ms] D/JITSI_MEET_PLUGIN(15785): JitsiMeetEventStreamHandler.onListen
[ +378 ms] E/flutter (15785): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: type 'Null' is not a subtype of type 'String' of
'function result'
[   +2 ms] E/flutter (15785): #0      _Location.file (package:flutter/src/widgets/widget_inspector.dart)
[   +1 ms] E/flutter (15785): #1      _Location.toJsonMap (package:flutter/src/widgets/widget_inspector.dart:2844:15)
[   +1 ms] E/flutter (15785): #2      _Location.toJsonMap.<anonymous closure> (package:flutter/src/widgets/widget_inspector.dart:2853:42)
[   +1 ms] E/flutter (15785): #3      MappedListIterable.elementAt (dart:_internal/iterable.dart:412:31)
[   +1 ms] E/flutter (15785): #4      ListIterator.moveNext (dart:_internal/iterable.dart:341:26)
[   +1 ms] E/flutter (15785): #5      new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:188:27)
[   +1 ms] E/flutter (15785): #6      new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
[   +2 ms] E/flutter (15785): #7      new List.of (dart:core-patch/array_patch.dart:50:28)
[   +1 ms] E/flutter (15785): #8      ListIterable.toList (dart:_internal/iterable.dart:212:44)
[   +1 ms] E/flutter (15785): #9      _Location.toJsonMap (package:flutter/src/widgets/widget_inspector.dart:2854:9)
[   +1 ms] E/flutter (15785): #10     InspectorSerializationDelegate.additionalNodeProperties
(package:flutter/src/widgets/widget_inspector.dart:3169:53)
[   +1 ms] E/flutter (15785): #11     DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1593:21)
[   +1 ms] E/flutter (15785): #12     DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1608:6)
[   +1 ms] E/flutter (15785): #13     DiagnosticsProperty.toJsonMap (package:flutter/src/foundation/diagnostics.dart:2694:45)
[   +1 ms] E/flutter (15785): #14     DiagnosticsNode.toJsonList.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1632:19)        
[   +1 ms] E/flutter (15785): #15     MappedListIterable.elementAt (dart:_internal/iterable.dart:412:31)
[   +1 ms] E/flutter (15785): #16     ListIterator.moveNext (dart:_internal/iterable.dart:341:26)
[   +1 ms] E/flutter (15785): #17     new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:188:27)
[   +1 ms] E/flutter (15785): #18     new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
[   +1 ms] E/flutter (15785): #19     new List.of (dart:core-patch/array_patch.dart:50:28)
[   +1 ms] E/flutter (15785): #20     ListIterable.toList (dart:_internal/iterable.dart:212:44)
[   +1 ms] E/flutter (15785): #21     DiagnosticsNode.toJsonList (package:flutter/src/foundation/diagnostics.dart:1633:8)
[   +1 ms] E/flutter (15785): #22     DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1595:25)
[   +1 ms] E/flutter (15785): #23     DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1608:6)
[   +1 ms] E/flutter (15785): #24     WidgetInspectorService._nodeToJson (package:flutter/src/widgets/widget_inspector.dart:1499:18)
[   +1 ms] E/flutter (15785): #25     WidgetInspectorService._reportError (package:flutter/src/widgets/widget_inspector.dart:919:44)
[   +2 ms] E/flutter (15785): #26     FlutterError.reportError (package:flutter/src/foundation/assertions.dart:1107:14)
[   +1 ms] E/flutter (15785): #27     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1146:20)
[   +1 ms] E/flutter (15785): #28     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1090:9)
[        ] E/flutter (15785): #29     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:998:5)
[        ] E/flutter (15785): #30     _rootRun (dart:async/zone.dart:1354:13)
[        ] E/flutter (15785): #31     _CustomZone.run (dart:async/zone.dart:1258:19)
[        ] E/flutter (15785): #32     _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
[        ] E/flutter (15785): #33     _invoke (dart:ui/hooks.dart:163:10)
[        ] E/flutter (15785): #34     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:259:5)
[        ] E/flutter (15785): #35     _drawFrame (dart:ui/hooks.dart:126:31)
[        ] E/flutter (15785): 
[ +123 ms] 
                    ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
                    The following assertion was thrown during a scheduler callback:
                    'package:flutter/src/rendering/binding.dart': Failed assertion: line 334 pos 12:
                    '!_debugMouseTrackerUpdateScheduled': is not true.

                    Either the assertion indicates an error in the framework itself, or we should provide substantially
                    more information in this error message to help you determine and fix the underlying cause.
                    In either case, please report this assertion by filing a bug on GitHub:
                      https://github.com/flutter/flutter/issues/new?template=2_bug.md

                    When the exception was thrown, this was the stack:
                    #2      RendererBinding._scheduleMouseTrackerUpdate (package:flutter/src/rendering/binding.dart:334:12)
                    #3      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:329:5)
                    #4      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
                    #5      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
                    #6      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:998:5)
                    #10     _invoke (dart:ui/hooks.dart:163:10)
                    #11     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:259:5)
                    #12     _drawFrame (dart:ui/hooks.dart:126:31)
                    (elided 5 frames from class _AssertionError and dart:async)
                    ════════════════════════════════════════════════════════════════════════════════════════════════════
[  +87 ms] 
           Another exception was thrown: 'package:flutter/src/rendering/binding.dart': Failed assertion: line 334 pos 12:
'!_debugMouseTrackerUpdateScheduled':
           is not true.
[ +142 ms] 
                    Another exception was thrown: 'package:flutter/src/rendering/binding.dart': Failed assertion: line 334 pos 12:
'!_debugMouseTrackerUpdateScheduled':
                    is not true.
[  +41 ms] 
           Another exception was thrown: 'package:flutter/src/rendering/binding.dart': Failed assertion: line 334 pos 12:
'!_debugMouseTrackerUpdateScheduled':
           is not true.
[+1056 ms] 
                    Another exception was thrown: 'package:flutter/src/rendering/binding.dart': Failed assertion: line 334 pos 12:
'!_debugMouseTrackerUpdateScheduled':
                    is not true.
[  +94 ms] 
           Another exception was thrown: 'package:flutter/src/rendering/binding.dart': Failed assertion: line 334 pos 12:
'!_debugMouseTrackerUpdateScheduled':
           is not true.
[ +908 ms] 
                    Another exception was thrown: 'package:flutter/src/rendering/binding.dart': Failed assertion: line 334 pos 12:
'!_debugMouseTrackerUpdateScheduled':
                    is not true.
[  +55 ms] 
           Another exception was thrown: 'package:flutter/src/rendering/binding.dart': Failed assertion: line 334 pos 12:
'!_debugMouseTrackerUpdateScheduled':
           is not true.
[ +903 ms] 
                    Another exception was thrown: 'package:flutter/src/rendering/binding.dart': Failed assertion: line 334 pos 12:
'!_debugMouseTrackerUpdateScheduled':
                    is not true.
[  +31 ms] 
           Another exception was thrown: 'package:flutter/src/rendering/binding.dart': Failed assertion: line 334 pos 12:
'!_debugMouseTrackerUpdateScheduled':
           is not true.
[ +986 ms] 
                    Another exception was thrown: 'package:flutter/src/rendering/binding.dart': Failed assertion: line 334 pos 12:
'!_debugMouseTrackerUpdateScheduled':
                    is not true.
[  +41 ms] 
           Another exception was thrown: 'package:flutter/src/rendering/binding.dart': Failed assertion: line 334 pos 12:
'!_debugMouseTrackerUpdateScheduled':
           is not true.
[  +95 ms] 
           Another exception was thrown: 'package:flutter/src/rendering/binding.dart': Failed assertion: line 334 pos 12:
'!_debugMouseTrackerUpdateScheduled':
           is not true.
[  +31 ms] 
           Another exception was thrown: 'package:flutter/src/rendering/binding.dart': Failed assertion: line 334 pos 12:
'!_debugMouseTrackerUpdateScheduled':
           is not true.
[  +36 ms] 
           Another exception was thrown: 'package:flutter/src/rendering/binding.dart': Failed assertion: line 334 pos 12:
'!_debugMouseTrackerUpdateScheduled':
           is not true.
[  +37 ms] D/JITSI_MEET_PLUGIN(15785): JitsiMeetEventStreamHandler.onCancel
[   +1 ms] D/JITSI_MEET_PLUGIN(15785): JitsiMeetEventStreamHandler.onListen
[   +4 ms] D/JITSI_MEET_PLUGIN(15785): method: joinMeeting
[   +1 ms] D/JITSI_MEET_PLUGIN(15785): arguments: {videoMuted=false, subject=TalkEng English Session, iosAppBarRGBAColor=null,
serverURL=https://meet.jit.si/, audioOnly=true, audioMuted=false, userDisplayName=ALOHA SpeedMaths Tripura, userEmail=sm-tr@mfalohaindia.com,
room=c1209fec-33d5-44a9-8f77-a34d4dea4b28, token=null, featureFlags={raise-hand.enabled=true, add-people.enabled=false, tile-view.enabled=true,       
meeting-password.enabled=false, pip.enabled=false, live-streaming.enabled=false, call-integration.enabled=false, chat.enabled=false,
invite.enabled=false, calendar.enabled=false, welcomepage.enabled=false, toolbox.alwaysVisible=true}}
[  +26 ms] 
           Another exception was thrown: 'package:flutter/src/rendering/binding.dart': Failed assertion: line 334 pos 12:
'!_debugMouseTrackerUpdateScheduled':
           is not true.
[  +24 ms] D/JITSI_MEET_PLUGIN(15785): Joining Room: c1209fec-33d5-44a9-8f77-a34d4dea4b28
[   +1 ms] D/JITSI_MEET_PLUGIN(15785): Server URL: https://meet.jit.si/, https://meet.jit.si/
[  +15 ms] I/Timeline(15785): Timeline: Activity_launch_request time:49360323
[  +25 ms] I/FIAM.Display(15785): Unbinding from activity: MainActivity
[        ] I/FIAM.Headless(15785): Removing display event component
[   +9 ms] W/ActivityThread(15785): handleWindowVisibility: no activity for token android.os.BinderProxy@e779f9
[  +22 ms] 
           Another exception was thrown: 'package:flutter/src/rendering/binding.dart': Failed assertion: line 334 pos 12:
'!_debugMouseTrackerUpdateScheduled':
           is not true.
[   +1 ms] D/ForceDarkHelper(15785): updateByCheckExcludeList: pkg: io.talkeng.app.global activity:
com.gunschu.jitsi_meet.JitsiMeetPluginActivity@d331ee
[   +2 ms] D/ForceDarkHelper(15785): updateByCheckExcludeList: pkg: io.talkeng.app.global activity:
com.gunschu.jitsi_meet.JitsiMeetPluginActivity@d331ee
[   +1 ms] D/ForceDarkHelper(15785): updateByCheckExcludeList: pkg: io.talkeng.app.global activity:
com.gunschu.jitsi_meet.JitsiMeetPluginActivity@d331ee
[   +2 ms] D/ForceDarkHelper(15785): updateByCheckExcludeList: pkg: io.talkeng.app.global activity:
com.gunschu.jitsi_meet.JitsiMeetPluginActivity@d331ee
[  +18 ms] D/ForceDarkHelper(15785): updateByCheckExcludeList: pkg: io.talkeng.app.global activity:
com.gunschu.jitsi_meet.JitsiMeetPluginActivity@d331ee

**Comment by jonasbark** [comment]
The error log does not seem to be related to stripe

**Comment by subhra9326** [comment]
Actually, when I am removing the stripe library, jitsi meet working well but when I add the stripe library, its meet gives Activity related errors like
[ +15 ms] I/Timeline(15785): Timeline: Activity_launch_request time:49360323
[ +25 ms] I/FIAM.Display(15785): Unbinding from activity: MainActivity.

I am guessing like Jitsimeet may need activity and stripes need fragment on MainActivity.

**Comment by bizready** [comment]
flutter_stripe: 1.2.0
jitsi_meet: ^4.0.0

As soon as I add jitsi_meet: ^4.0.0, I get the following errors:


E/AndroidRuntime(23591): java.lang.NoSuchMethodError: No direct method <init>(Landroid/content/Context;Lio/flutter/plugin/common/MethodChannel;)V in class Lcom/facebook/react/uimanager/ThemedReactContext; or its super classes (declaration of 'com.facebook.react.uimanager.ThemedReactContext' appears in /data/app/~~BOwBhISGY7qkM3n4357wjg==/com.myappdash.app-IUTXF2jCfxgNppyae33Cpg==/base.apk!classes3.dex)
E/AndroidRuntime(23591): 	at com.flutter.stripe.StripeSdkCardPlatformView.<init>(StripeSdkCardPlatformView.kt:31)
E/AndroidRuntime(23591): 	at com.flutter.stripe.StripeSdkCardPlatformViewFactory.create(StripeSdkCardPlatformViewFactory.kt:19)
E/AndroidRuntime(23591): 	at io.flutter.plugin.platform.PlatformViewsController$1.createAndroidViewForPlatformView(PlatformViewsController.java:146)
E/AndroidRuntime(23591): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:101)

**Comment by jamesblasco** [comment]
Please if the problem is still occurring I suggest creating a new issue where you detail the version of each package, the logs, device and confirm that your app works with only flutter_stripe and you have followed the steps required to make it to work with Android.

**Comment by ektapadaliya44** [comment]
@subhra9326  Did you find any solution to work jitsi and stripe togather?

**Comment by shalini-kad** [comment]
Is there any update on this issue..Any idea what is causing the incompatibility between the packages?  @jonasbark @ektapadaliya44

**Comment by lucasvps** [comment]
@jonasbark Hey man, did you found any solution for this?

**Comment by denes16** [comment]
Any solution @lucasvps ?

**Comment by mbebs** [comment]
Any solution? This is still an issue
