### ISSUE TITLE
Unhandled Exception: type 'Null' is not a subtype of type 'Map<String, dynamic>'

### ISSUE THREAD

**Issue by uzirthapa** [flutter-stripe/flutter_stripe#206]
**Describe the bug**

Just converted my project to Null Safety and now this function stopped working correctly. 

```
Stripe.instance.confirmSetupIntent(
                                  clientSecret,
                                  PaymentMethodParams.card(
                                    billingDetails: billingDetails,
                                  ),
                                );
```

When looking at the stack trace it is giving me an error 

```
 Unhandled Exception: type 'Null' is not a subtype of type 'Map<String, dynamic>'
```

Stack Trace:

```
Unhandled Exception: type 'Null' is not a subtype of type 'Map<String, dynamic>'
#0      MethodChannelStripe.confirmSetupIntent (package:stripe_platform_interface/src/method_channel_stripe.dart:114:36)
<asynchronous suspension>
#1      Stripe.confirmSetupIntent (package:flutter_stripe/src/stripe.dart:259:27)
<asynchronous suspension>
```

**To Reproduce**

-Get Client Secret from SetupIntent

```
 final clientSecret =
                                    await _paymentService.setupIntent(
                                        customerId: "YOUR CUSTOMER ID");
```

- Add a credit card "4242-4242-4242-4242" with billing details and call this function: 

```
final setupIntentResult =
                                    await Stripe.instance.confirmSetupIntent(
                                  clientSecret,
                                  PaymentMethodParams.card(
                                    billingDetails: billingDetails,
                                  ),
                                );

```

**Expected behavior**

Expected a return of the setupIntentResult

**Smartphone / tablet**
 - Device: [iPhone XR]
 - OS: [iOS 14]
 - Package version: [1.1.0]
 - Flutter version [2.2.3]

**Comment by uzirthapa** [comment]
Sorry My Mistake. Forgot to add the publishable Stripe Key.
