### ISSUE TITLE
Null Pointer Exception while submitting CardField in Android.

### ISSUE THREAD

**Issue by IronLad85** [flutter-stripe/flutter_stripe#289]
**Describe the bug**
Java Null Pointer Exception while adding a card using CardField widget in Android. However this error doesn't happen in iOS.

** Error Message**
```
Failed to handle method call
java.lang.NullPointerException at com.reactnativestripesdk.PaymentMethodCreateParamsFactory.createCardPaymentSetupParams(PaymentMethodCreateParamsFactory.kt:161)
 	at com.reactnativestripesdk.PaymentMethodCreateParamsFactory.createSetupParams(PaymentMethodCreateParamsFactory.kt:41)
	at com.reactnativestripesdk.StripeSdkModule.confirmSetupIntent(StripeSdkModule.kt:485)
	at com.flutter.stripe.StripeAndroidPlugin.onMethodCall(StripeAndroidPlugin.kt:68)
	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:84)
        at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:865)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:335)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:8060)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
```

**To Reproduce**
1. Add details inside CardField in android.
2. Try to add the Card.
3. Observe a failure with exception (including the part of the stack trace, belonging to this package) …

**Expected behavior**
Card being added successfully after adding all the details and submitting it.

**Smartphone / tablet**
 - Device: [Redmi Note 10 Pro]
 - OS: [Android 10]
 - Package version: [1.2.0]
 - Flutter version [Flutter 2.5.0-7.0.pre.8]

**Comment by jonasbark** [comment]
Thanks for reporting. Which test card details are you using where this is reproducible?

**Comment by IronLad85** [comment]
@jonasbark  
It occurs on any test card details.
I tried below info
Card No - 4242 4242 4242 4242
Expiry 03/23
CVC 233

**Comment by jonasbark** [comment]
1. Please confirm that this is an issue on the example app as well
2. Please share a reproducible example if it isn't

**Comment by IronLad85** [comment]
This is the code I am using to add a card using card field in UI. It's working fine in iOS but in android it's crashing with the error I mentioned above.

```
static Future<void> addUserPaymentCard(context) async {
    // 1. create payment intent on the server.

    MainStore mainStore = Provider.of<MainStore>(context, listen: false);
    Map userData = mainStore.authStore.userProfile;
    String stripeCustomerId = userData['stripe_customer_id'];
    Map setupIntentData = await ArrivalSlotService.initStripeSetupIntent(stripeCustomerId);
     if (setupIntentData['error'] != null) {
      return;
    }

    try {
      await Stripe.instance.confirmSetupIntent(
        setupIntentData['intent']['client_secret'],
        PaymentMethodParams.card(
          setupFutureUsage: PaymentIntentsFutureUsage.OffSession,
          billingDetails: BillingDetails(
            email: '${userData['email'] ?? 'test@mail.com'}',
            name:
                '${userData['first_name'] ?? ''} ${userData['last_time'] ?? ''}',
            phone: '${userData['mobile_no'] ?? ''}',
            address: Address(
              city: "Test City",
              line1: "Test Address 1",
              line2: "Test Adress 2",
              state: "Test State",
              postalCode: "56005",
              country: "Test Country",
            ),
          ),
        ),
      );
    } catch (err) {
      print("PAYMENT ERR  -> ${err.error}");
    }
  }
```

**Comment by jonasbark** [comment]
what was the issue?
