### ISSUE TITLE
Payment Sheet android crash

### ISSUE THREAD

**Issue by mzl1988** [flutter-stripe/flutter_stripe#331]
```
[✓] Flutter (Channel stable, 2.5.0, on macOS 11.5.1 20G80
    darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google
    Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.60.0)
[✓] Connected device (1 available)


D/AndroidRuntime( 3902): Shutting down VM
E/AndroidRuntime( 3902): FATAL EXCEPTION: main
E/AndroidRuntime( 3902): Process: flutter.payment.test, PID: 3902
E/AndroidRuntime( 3902): java.lang.NoSuchMethodError: No direct method <init>(Ljava/lang/String;Lcom/stripe/android/paymentsheet/PaymentSheet$CustomerConfiguration;Lcom/stripe/android/paymentsheet/PaymentSheet$GooglePayConfiguration;Landroid/content/res/ColorStateList;ILkotlin/jvm/internal/DefaultConstructorMarker;)V in class Lcom/stripe/android/paymentsheet/PaymentSheet$Configuration; or its super classes (declaration of 'com.stripe.android.paymentsheet.PaymentSheet$Configuration' appears in /data/app/~~p5FL7pyWMnvMTTUq1CGYZQ==/flutter.payment.test-R9YSVv6PID6OTbuxHWLnUg==/base.apk!classes3.dex)
E/AndroidRuntime( 3902):        at com.reactnativestripesdk.PaymentSheetFragment.onViewCreated(PaymentSheetFragment.kt:74)
E/AndroidRuntime( 3902):        at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:2987)
E/AndroidRuntime( 3902):        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:546)
E/AndroidRuntime( 3902):        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
E/AndroidRuntime( 3902):        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
E/AndroidRuntime( 3902):        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
E/AndroidRuntime( 3902):        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
E/AndroidRuntime( 3902):        at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:524)
E/AndroidRuntime( 3902):        at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime( 3902):        at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 3902):        at android.os.Looper.loop(Looper.java:246)
E/AndroidRuntime( 3902):        at android.app.ActivityThread.main(ActivityThread.java:8587)
E/AndroidRuntime( 3902):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 3902):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
E/AndroidRuntime( 3902):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
I/Process ( 3902): Sending signal. PID: 3902 SIG: 9
Lost connection to device.
```

**Comment by jonasbark** [comment]
Can you reproduce this in the example application? If you can't then please provide a reproducible example.

**Comment by natebgurutech** [comment]
I'm having the exact same issue.

**Comment by kelvin265** [comment]
Am also having the same issue

**Comment by rynld** [comment]
I'm having the same issue. The problem is adding this line to the build.gradle
`    implementation 'com.stripe:stripe-android:17.1.2'
`
If I remove the line the payment sheet works. However the Google Pay Button is not shown.

Here is the complete error:

`
E/AndroidRuntime(18763): 	at android.app.ActivityThread.main(ActivityThread.java:6863)
E/AndroidRuntime(18763): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(18763): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
E/AndroidRuntime(18763): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

`

**Comment by joeloudjinz** [comment]
I faced the same exact issue of @rynld 

> I'm having the same issue. The problem is adding this line to the build.gradle
> ` implementation 'com.stripe:stripe-android:17.1.2'`
> If I remove the line the payment sheet works. However the Google Pay Button is not shown.

**Comment by jonasbark** [comment]
You should not overwrite the android dependency yourself.
Google Pay Button not showing would be an entirely different issue.

Please provide a reproducible example application where you experience the crash.

**Comment by natebgurutech** [comment]
I can't really get you runnable code very easily, all of our use cases are very sensitive and use our own Stripe keys and such.  Basically, if you use the example code as intended it will break as far as I can tell, but since you're asking over and over for some code to run here's some code you can look at.  It won't run as is, there are a lot of pieces that need aggregating that you will need to go get to make it run on your own machine.

```
Future<Response<dynamic>> fetchEphemeralKeys() async {
  try {
    Response response = await dio.get(
      '/$resource/ephemeral_keys/',
      options: this.options(RestMethods.get),
    );
    return response;
  } on DioError catch (e) {
    if (await this.authService.checkForRefresh(e))
      return await this.fetchEphemeralKeys();
    return e.response;
  }
}

final resp = await this.stripeApi.createPaymentIntent();
if (200 <= resp.statusCode && resp.statusCode < 300) {
this._paymentSheetData = resp.data;
final ephResp = await this.stripeApi.fetchEphemeralKeys();
if (200 <= ephResp.statusCode && ephResp.statusCode < 300) {
    // 2. initialize the payment sheet
    var params = SetupPaymentSheetParameters(
    applePay: Stripe.instance.isApplePaySupported.value,
    googlePay: true,
    style: ThemeMode.light,
    testEnv: isTestMode,
    merchantCountryCode: 'US',
    merchantDisplayName: 'TEST',
    customerId: _paymentSheetData['customer'],
    paymentIntentClientSecret: _paymentSheetData['secret'],
    customerEphemeralKeySecret: ephResp.data['id'],
    );
    // TODO: Watch for an update to flutter_stripe then uncomment
    //       flutter_stripe 1.3.0 (the current version as of writing this) has an issue
    //       initializing the payment sheet. We need to watch for an update.
    //       https://github.com/flutter-stripe/flutter_stripe/issues/331
    // await Stripe.instance.initPaymentSheet(paymentSheetParameters: params);
}
```
