### ISSUE TITLE
Successful payment on Stripe failed with Exception on Android

### ISSUE THREAD

**Issue by AGKireev** [flutter-stripe/flutter_stripe#341]
**Describe the bug**
Found a successful payment on Stripe which raised exception in the app.
Crashlytics logs show the following:
```
Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: StripeException(error: LocalizedErrorMessage(code: FailureCode.Failed, localizedMessage: A PaymentIntent with status='requires_payment_method' is required.
The current PaymentIntent has status succeeded.
See https://stripe.com/docs/api/payment_intents/object#payment_intent_object-status., message: A PaymentIntent with status='requires_payment_method' is required.
The current PaymentIntent has status succeeded.
See https://stripe.com/docs/api/payment_intents/object#payment_intent_object-status., stripeErrorCode: null, declineCode: null, type: null)). Error thrown null.
       at MethodChannelStripe._parsePaymentSheetResult(MethodChannelStripe.java:225)
       at MethodChannelStripe.presentPaymentSheet(MethodChannelStripe.java:183)
       at Stripe.presentPaymentSheet(Stripe.java:309)
       at OrderButton._pay(OrderButton.java:178)
       at OrderButton.finalizeOrder(OrderButton.java:120)
```

**To Reproduce**
Couldn't reproduce it myself.

**Expected behavior**
No exception.

**Smartphone / tablet**
 - Device: Samsung Galaxy M12
 - OS: Android 11
 - Package version: 1.2.0
 - Flutter version 2.2.2

**Additional context**
Payment sheet initialized with the following data:
```
stripe.Stripe.instance.initPaymentSheet(
      paymentSheetParameters: stripe.SetupPaymentSheetParameters(
        customerId: customerId,
        paymentIntentClientSecret: createOrderResponse.stripeClientSecret,
        customerEphemeralKeySecret: createOrderResponse.stripeEphemeralKey,
        merchantDisplayName: '*REMOVED*',
        merchantCountryCode: 'CZ',
        applePay: true,
        googlePay: true,
        testEnv: false,
        style: ThemeMode.light,
      ),
    )
```
Payment sheet presented using the following config:

```
stripe.Stripe.instance.presentPaymentSheet(
      parameters: stripe.PresentPaymentSheetParameters(
        clientSecret: createOrderResponse.stripeClientSecret,
        confirmPayment: true,
      ),
    )
```

**Comment by remonh87** [comment]
these error are thrown by the Stripe SDK I assume the payment sheet was used with a client secret that was already paid.  I would check your implementation of the payment sheet.
