### ISSUE TITLE
App crashes on confirmPayment with GooglePay

### ISSUE THREAD

**Issue by pawelpetruch** [flutter-stripe/flutter_stripe#376]
**Describe the bug**
App crashes when confirm payment using GooglePay. Cards work fine.

**To Reproduce**
Call initPaymentSheet, presentPaymentSheet, select GooglePay and then call confirmPayment.
``` 
 Future<CreatePaymentSheetModel> _createPaymentSheet() async {
    final url = Uri.parse('${Constants.kStripeLocalApiUrl}/payment-sheet');
    // TOOD: Remove this
    final payload = json.encode({
      'a': 'a',
    });
    final response = await httpService.postRequest(url.toString(), payload);
    if (response != null && response.statusCode! > 200) {
      throw Exception(
          'StripeController - Exception when trying to create payment sheet: ${response.statusMessage}');
    }
    final result =
        CreatePaymentSheetModel.fromMap(response!.data as Map<String, dynamic>);
    return result;
  }

  Future<void> initPaymentSheet() async {
    // 1. Create payment sheet
    final data = await _createPaymentSheet();

    // 2. Init Payment Sheet
    await Stripe.instance.initPaymentSheet(
      paymentSheetParameters: SetupPaymentSheetParameters(
        // Enable custom flow
        customFlow: true,
        // Main params
        merchantDisplayName: 'name',
        paymentIntentClientSecret: data.paymentIntent,
        // Customer keys
        customerEphemeralKeySecret: data.ephemeralKey,
        customerId: data.customerId,
        // Extra options
        // TODO: Make that variable dependent
        testEnv: true,
        applePay: true,
        googlePay: true,
        style: ThemeMode.dark,
      ),
    );
  }

  Future<void> presentPaymentSheet() async {
    // 3. Display the payment sheet.
    await Stripe.instance.presentPaymentSheet();
  }

  Future<void> confirmPayment() async {
    // 4. Confirm the payment sheet.
    await Stripe.instance.confirmPaymentSheetPayment();
  }
```

**Expected behavior**

**Smartphone / tablet**
 - Device: Android
 - Package version: 1.3.0
 - Flutter version 2.5.1

**Additional context**
```
E/AndroidRuntime(29668): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1585680034, result=-1, data=Intent { (has extras) }} to activity {com...com...MainActivity}: java.lang.RuntimeException: Parcelable encountered IOException writing serializable object (name = com.stripe.android.paymentsheet.flowcontroller.DefaultFlowController$GooglePayException)
E/AndroidRuntime(29668): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5015)
E/AndroidRuntime(29668): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5056)
E/AndroidRuntime(29668): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
E/AndroidRuntime(29668): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(29668): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(29668): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
E/AndroidRuntime(29668): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(29668): 	at android.os.Looper.loop(Looper.java:223)
E/AndroidRuntime(29668): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/AndroidRuntime(29668): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(29668): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/AndroidRuntime(29668): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/AndroidRuntime(29668): Caused by: java.lang.RuntimeException: Parcelable encountered IOException writing serializable object (name = com.stripe.android.paymentsheet.flowcontroller.DefaultFlowController$GooglePayException)
E/AndroidRuntime(29668): 	at android.os.Parcel.writeSerializable(Parcel.java:2113)
E/AndroidRuntime(29668): 	at com.stripe.android.paymentsheet.PaymentSheetResult$Failed.writeToParcel(Unknown Source:9)
E/AndroidRuntime(29668): 	at android.os.Parcel.writeParcelable(Parcel.java:1904)
E/AndroidRuntime(29668): 	at android.os.Parcel.writeValue(Parcel.java:1810)
E/AndroidRuntime(29668): 	at android.os.Parcel.writeArrayMapInternal(Parcel.java:975)
E/AndroidRuntime(29668): 	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1620)
E/AndroidRuntime(29668): 	at android.os.Bundle.writeToParcel(Bundle.java:1303)
E/AndroidRuntime(29668): 	at android.os.Parcel.writeBundle(Parcel.java:1044)
E/AndroidRuntime(29668): 	at android.content.Intent.writeToParcel(Intent.java:10855)
E/AndroidRuntime(29668): 	at android.app.IActivityManager$Stub$Proxy.broadcastIntentWithFeature(IActivityManager.java:5499)
E/AndroidRuntime(29668): 	at android.app.ContextImpl.sendBroadcast(ContextImpl.java:1115)
E/AndroidRuntime(29668): 	at android.content.ContextWrapper.sendBroadcast(ContextWrapper.java:468)
E/AndroidRuntime(29668): 	at com.reactnativestripesdk.PaymentSheetFragment$onViewCreated$paymentResultCallback$1.onPaymentSheetResult(PaymentSheetFragment.kt:70)
E/AndroidRuntime(29668): 	at com.stripe.android.paymentsheet.flowcontroller.DefaultFlowController.onGooglePayResult$payments_core_release(DefaultFlowController.kt:307)
E/AndroidRuntime(29668): 	at com.stripe.android.paymentsheet.flowcontroller.-$$Lambda$PtEwmX01qgVGwQFga0rIpWjQILs.onActivityResult(Unknown Source:4)
E/AndroidRuntime(29668): 	at androidx.activity.result.ActivityResultRegistry.doDispatch(ActivityResultRegistry.java:392)
E/AndroidRuntime(29668): 	at androidx.activity.result.ActivityResultRegistry.dispatchResult(ActivityResultRegistry.java:351)
E/AndroidRuntime(29668): 	at androidx.activity.ComponentActivity.onActivityResult(ComponentActivity.java:638)
E/AndroidRuntime(29668): 	at androidx.fragment.app.FragmentActivity.onActivityResult(FragmentActivity.java:164)
E/AndroidRuntime(29668): 	at io.flutter.embedding.android.FlutterFragmentActivity.onActivityResult(FlutterFragmentActivity.java:533)
E/AndroidRuntime(29668): 	at android.app.Activity.dispatchActivityResult(Activity.java:8310)
E/AndroidRuntime(29668): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5008)
E/AndroidRuntime(29668): 	... 11 more
E/AndroidRuntime(29668): Caused by: java.io.NotSerializableException: com.google.android.gms.common.api.Status
E/AndroidRuntime(29668): 	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1240)
E/AndroidRuntime(29668): 	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1604)
E/AndroidRuntime(29668): 	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1565)
E/AndroidRuntime(29668): 	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1488)
E/AndroidRuntime(29668): 	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
E/AndroidRuntime(29668): 	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:354)
E/AndroidRuntime(29668): 	at android.os.Parcel.writeSerializable(Parcel.java:2108)
E/AndroidRuntime(29668): 	... 32 more

**Comment by jonasbark** [comment]
I've been unable to reproduce this on the example application. Can you try it there as well?

The 
> PaymentSheetResult$Failed

part in the logs could indicate issues with your keys.

**Comment by pawelpetruch** [comment]
That was my bad, I didn't set up the AppCompat style in AndroidManifest files.
