### ISSUE TITLE
[CRASH] StripeSdkModule.java com.reactnativestripesdk.StripeSdkModule$mPaymentSheetReceiver$1.onReceive

### ISSUE THREAD

**Issue by bhanuka96** [flutter-stripe/flutter_stripe#389]
App crash after upgrade the plugin. It's not happening all the time. 

version `flutter_stripe: ^2.0.0`

```
Fatal Exception: java.lang.NullPointerException: null cannot be cast to non-null type com.reactnativestripesdk.PaymentSheetFragment
       at com.reactnativestripesdk.StripeSdkModule$mPaymentSheetReceiver$1.onReceive(StripeSdkModule.java:51)
       at androidx.localbroadcastmanager.content.LocalBroadcastManager.a(LocalBroadcastManager.java:59)
       at androidx.localbroadcastmanager.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:11)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8587)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

**Comment by remonh87** [comment]
@bhanuka96  we really need a bit more in order to help you out so we really need a proper reproduction scenario.

**Comment by remonh87** [comment]
You are sure that you followed: https://github.com/flutter-stripe/flutter_stripe#android?  Can you  share the code of the paymentsheet initialisation?

**Comment by bhanuka96** [comment]
**Initial Setup**

```
// this class is singelton

  Future<ConfigBookingModel> getConfigBooking() async {
    if (configBookingModel != null) return configBookingModel;

    return _db.collection('systemconfig').doc('booking').get().then((value) {

      configBookingModel = ConfigBookingModel.fromFirestore(value);
      Stripe.publishableKey = configBookingModel?.stripeModel?.pk;
      Stripe.stripeAccountId = configBookingModel?.stripeModel?.accId;
      Stripe.merchantIdentifier = configBookingModel?.stripeModel?.merchantIdentifier;
      Stripe.urlScheme = configBookingModel?.stripeModel?.urlScheme;

      return configBookingModel;
    });
  }
```

**handle stripe payment**
 ```
 void stripePaymentHandler(PaymentResponse model) async {
    try {
      await db.getConfigBooking();
      await Stripe.instance.initPaymentSheet(
        paymentSheetParameters: SetupPaymentSheetParameters(
            paymentIntentClientSecret: model?.stripeResModel?.paymentIntent,
            merchantDisplayName: 'companyName',
            customerId: model?.stripeResModel?.customer,
            customerEphemeralKeySecret: model?.stripeResModel?.ephemeralKey,
            applePay: true,
            googlePay: true,
            style: ThemeMode.system,
            testEnv: env.flavor == BuildFlavor.development,
            merchantCountryCode: 'AE'
            ),
      );
    await Stripe.instance.presentPaymentSheet();
    requirement?.resetData();
    Navigator.pushNamedAndRemoveUntil(buildContext, '/bookingStatusPage', ModalRoute.withName('/dashboard'));
    } on Exception catch (e) {
      if (e is StripeException) {
        error(e.error.localizedMessage);
      } else {
        error('$e');
      }
    }
  }

```

**Comment by nicks258** [comment]
Suddenly facing this crash!!. Any updates?

**Comment by remonh87** [comment]
Closed, Difficult to reproduce. Feel free to reopen it with additional info.

**Comment by remonh87** [comment]
found this as well in my production app am investigating it

**Comment by remonh87** [comment]
Created a potential bug fix  I think this should make things better. Also I realised this bug is similar (however stack trace is different) with #416. I propose to continue on that issue and close this one
