### ISSUE TITLE
CardField is not displayed on some Android devices.

### ISSUE THREAD

**Issue by sakyoyuto** [flutter-stripe/flutter_stripe#398]
Hi, thanks for any help with this.

There is a bug that CardField is not displayed on some Android devices (Pixel, AQUOS).
However, the problem is complicated as some devices still display the cardfield even if the same model of Pixel is used.

The errors that are displayed are as below.
```
E/MethodChannel#flutter/platform_views(30081): Failed to handle method call
E/MethodChannel#flutter/platform_views(30081): android.view.InflateException: Binary XML file line #22 in {appId}:layout/card_input_widget: Binary XML file line #22 in {appId}:layout/card_input_widget: Error inflating class com.google.android.material.textfield.TextInputLayout
E/MethodChannel#flutter/platform_views(30081): Caused by: android.view.InflateException: Binary XML file line #22 in {appId}:layout/card_input_widget: Error inflating class com.google.android.material.textfield.TextInputLayout
E/MethodChannel#flutter/platform_views(30081): Caused by: java.lang.reflect.InvocationTargetException
E/MethodChannel#flutter/platform_views(30081):  at java.lang.reflect.Constructor.newInstance0(Native Method)
E/MethodChannel#flutter/platform_views(30081):  at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
E/MethodChannel#flutter/platform_views(30081):  at android.view.LayoutInflater.createView(LayoutInflater.java:858)
E/MethodChannel#flutter/platform_views(30081):  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1010)
E/MethodChannel#flutter/platform_views(30081):  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
E/MethodChannel#flutter/platform_views(30081):  at android.view.LayoutInflater.rInflate(LayoutInflater.java:1127)
E/MethodChannel#flutter/platform_views(30081):  at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
E/MethodChannel#flutter/platform_views(30081):  at android.view.LayoutInflater.rInflate(LayoutInflater.java:1130)
E/MethodChannel#flutter/platform_views(30081):  at android.view.LayoutInflater.inflate(LayoutInflater.java:660)
E/MethodChannel#flutter/platform_views(30081):  at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
E/MethodChannel#flutter/platform_views(30081):  at android.view.LayoutInflater.inflate(LayoutInflater.java:485)
E/MethodChannel#flutter/platform_views(30081):  at com.stripe.android.databinding.CardInputWidgetBinding.inflate(CardInputWidgetBinding.java:88)
E/MethodChannel#flutter/platform_views(30081):  at com.stripe.android.view.CardInputWidget.<init>(CardInputWidget.kt:62)
E/MethodChannel#flutter/platform_views(30081):  at com.stripe.android.view.CardInputWidget.<init>(CardInputWidget.kt:56)
E/MethodChannel#flutter/platform_views(30081):  at com.reactnativestripesdk.StripeSdkCardView.<init>(StripeSdkCardView.kt:35)
E/MethodChannel#flutter/platform_views(30081):  at com.reactnativestripesdk.StripeSdkCardViewManager.createViewInstance(StripeSdkCardViewManager.kt:58)
E/MethodChannel#flutter/platform_views(30081):  at com.flutter.stripe.StripeSdkCardPlatformView.<init>(StripeSdkCardPlatformView.kt:33)
E/MethodChannel#flutter/platform_views(30081):  at com.flutter.stripe.StripeSdkCardPlatformViewFactory.create(StripeSdkCardPlatformViewFactory.kt:21)
E/MethodChannel#flutter/platform_views(30081):  at io.flutter.plugin.platform.PlatformViewsController$1.createAndroidViewForPlatformView(PlatformViewsController.java:151)
E/MethodChannel#flutter/platform_views(30081):  at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:104)
E/MethodChannel#flutter/platform_views(30081):  at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:59)
E/MethodChannel#flutter/platform_views(30081):  at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#flutter/platform_views(30081):  at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:84)
E/MethodChannel#flutter/platform_views(30081):  at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:865)
E/MethodChannel#flutter/platform_views(30081):  at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter/platform_views(30081):  at android.os.MessageQueue.next(MessageQueue.java:335)
E/MethodChannel#flutter/platform_views(30081):  at android.os.Looper.loopOnce(Looper.java:161)
E/MethodChannel#flutter/platform_views(30081):  at android.os.Looper.loop(Looper.java:288)
E/MethodChannel#flutter/platform_views(30081):  at android.app.ActivityThread.main(ActivityThread.java:7842)
E/MethodChannel#flutter/platform_views(30081):  at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter/platform_views(30081):  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/MethodChannel#flutter/platform_views(30081):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
E/MethodChannel#flutter/platform_views(30081): Caused by: java.lang.IllegalArgumentException: The style on this component requires your app theme to be Theme.AppCompat (or a descendant).
E/MethodChannel#flutter/platform_views(30081):  at com.google.android.material.internal.ThemeEnforcement.checkTheme(ThemeEnforcement.java:243)
E/MethodChannel#flutter/platform_views(30081):  at com.google.android.material.internal.ThemeEnforcement.checkAppCompatTheme(ThemeEnforcement.java:213)
E/MethodChannel#flutter/platform_views(30081):  at com.google.android.material.internal.ThemeEnforcement.checkCompatibleTheme(ThemeEnforcement.java:148)
E/MethodChannel#flutter/platform_views(30081):  at com.google.android.material.internal.ThemeEnforcement.obtainTintedStyledAttributes(ThemeEnforcement.java:115)
E/MethodChannel#flutter/platform_views(30081):  at com.google.android.material.textfield.TextInputLayout.<init>(TextInputLayout.java:469)
E/MethodChannel#flutter/platform_views(30081):  at com.google.android.material.textfield.TextInputLayout.<init>(TextInputLayout.java:428)
E/MethodChannel#flutter/platform_views(30081):  ... 32 more
E/flutter (30081): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(error, Binary XML file line #22 in {appId}:layout/card_input_widget: Binary XML file line #22 in {appId}:layout/card_input_widget: Error inflating class com.google.android.material.textfield.TextInputLayout, null, android.view.InflateException: Binary XML file line #22 in {appId}:layout/card_input_widget: Binary XML file line #22 in {appId}:layout/card_input_widget: Error inflating class com.google.android.material.textfield.TextInputLayout
E/flutter (30081): Caused by: android.view.InflateException: Binary XML file line #22 in {appId}:layout/card_input_widget: Error inflating class com.google.android.material.textfield.TextInputLayout
E/flutter (30081): Caused by: java.lang.reflect.InvocationTargetException
E/flutter (30081):      at java.lang.reflect.Constructor.newInstance0(Native Method)
E/flutter (30081):      at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
E/flutter (30081):      at android.view.LayoutInflater.createView(LayoutInflater.java:858)
E/flutter (30081):      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1010)
E/flutter (30081):      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
E/flutter (30081):      at android.view.LayoutInflater.rInflate(LayoutInflater.java:1127)
E/flutter (30081):      at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
E/flutter (30081):      at android.view.LayoutInflater.rInflate(LayoutInflater.java:1130)
E/flutter (30081):      at android.view.LayoutInflater.inflate(LayoutInflater.java:660)
E/flutter (30081):      at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
E/flutter (30081):      at android.view.LayoutInflater.inflate(LayoutInflater.java:485)
E/flutter (30081):      at com.stripe.android.databinding.CardInputWidgetBinding.inflate(CardInputWidgetBinding.java:88)
E/flutter (30081):      at com.stripe.android.view.CardInputWidget.<init>(CardInputWidget.kt:62)
E/flutter (30081):      at com.stripe.android.view.CardInputWidget.<init>(CardInputWidget.kt:56)
E/flutter (30081):      at com.reactnativestripesdk.StripeSdkCardView.<init>(StripeSdkCardView.kt:35)
E/flutter (30081):      at com.reactnativestripesdk.StripeSdkCardViewManager.createViewInstance(StripeSdkCardViewManager.kt:58)
E/flutter (30081):      at com.flutter.stripe.StripeSdkCardPlatformView.<init>(StripeSdkCardPlatformView.kt:33)
E/flutter (30081):      at com.flutter.stripe.StripeSdkCardPlatformViewFactory.create(StripeSdkCardPlatformViewFactory.kt:21)
E/flutter (30081):      at io.flutter.plugin.platform.PlatformViewsController$1.createAndroidViewForPlatformView(PlatformViewsController.java:151)
E/flutter (30081):      at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:104)
E/flutter (30081):      at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:59)
E/flutter (30081):      at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/flutter (30081):      at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:84)
E/flutter (30081):      at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:865)
E/flutter (30081):      at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (30081):      at android.os.MessageQueue.next(MessageQueue.java:335)
E/flutter (30081):      at android.os.Looper.loopOnce(Looper.java:161)
E/flutter (30081):      at android.os.Looper.loop(Looper.java:288)
E/flutter (30081):      at android.app.ActivityThread.main(ActivityThread.java:7842)
E/flutter (30081):      at java.lang.reflect.Method.invoke(Native Method)
E/flutter (30081):      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/flutter (30081):      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
E/flutter (30081): Caused by: java.lang.IllegalArgumentException: The style on this component requires your app theme to be Theme.AppCompat (or a descendant).
E/flutter (30081):      at com.google.android.material.internal.ThemeEnforcement.checkTheme(ThemeEnforcement.java:243)
E/flutter (30081):      at com.google.android.material.internal.ThemeEnforcement.checkAppCompatTheme(ThemeEnforcement.java:213)
E/flutter (30081):      at com.google.android.material.internal.ThemeEnforcement.checkCompatibleTheme(ThemeEnforcement.java:148)
E/flutter (30081):      at com.google.android.material.internal.ThemeEnforcement.obtainTintedStyledAttributes(ThemeEnforcement.java:115)
E/flutter (30081):      at com.google.android.material.textfield.TextInputLayout.<init>(TextInputLayout.java:469)
E/flutter (30081):      at com.google.android.material.textfield.TextInputLayout.<init>(TextInputLayout.java:428)
E/flutter (30081):      ... 32 more
E/flutter (30081): )
E/flutter (30081): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
E/flutter (30081): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
E/flutter (30081): <asynchronous suspension>
E/flutter (30081): #2      AndroidViewController.create (package:flutter/src/services/platform_views.dart:771:5)
E/flutter (30081): <asynchronous suspension>
```

The docter is below.
```
[✓] Flutter (Channel stable, 2.5.2, on macOS 11.6 20G165 darwin-arm, locale
    ja-JP)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.61.1)
[✓] Connected device (3 available)

• No issues found!
```

Thank you.

**Comment by jonasbark** [comment]
> The style on this component requires your app theme to be Theme.AppCompat (or a descendant).

Please check the readme for Android:
https://github.com/flutter-stripe/flutter_stripe#android
