### ISSUE TITLE
Only on Web: Error: Unsupported operation: Platform._operatingSystem

### ISSUE THREAD

**Issue by ehcpdeveloper** [flutter-stripe/flutter_stripe#401]
flutter_stripe: ^2.0.0
flutter 2.5.3

Occurs only in web:
Raising directly exception in main.dart, in which it is required to initialize Stripe.

`Error: Unsupported operation: Platform._operatingSystem
    at Object.throw_ [as throw] (http://localhost:60806/store2/dart_sdk.js:5374:11)
    at Function._operatingSystem (http://localhost:60806/store2/dart_sdk.js:57970:17)
    at Function.get operatingSystem [as operatingSystem] (http://localhost:60806/store2/dart_sdk.js:58016:27)
    at get _operatingSystem (http://localhost:60806/store2/dart_sdk.js:57929:27)
    at Function.desc.get [as _operatingSystem] (http://localhost:60806/store2/dart_sdk.js:5881:17)
    at get isIOS (http://localhost:60806/store2/dart_sdk.js:57953:26)
    at Function.desc.get [as isIOS] (http://localhost:60806/store2/dart_sdk.js:5881:17)
    at MethodChannelStripeFactory.create (http://localhost:60806/store2/packages/stripe_platform_interface/src/result_parser.dart.lib.js:470:122)
    at get _instance (http://localhost:60806/store2/packages/stripe_platform_interface/src/result_parser.dart.lib.js:216:30)
    at Function.desc.get [as _instance] (http://localhost:60806/store2/dart_sdk.js:5881:17)
    at Function.get instance [as instance] (http://localhost:60806/store2/packages/stripe_platform_interface/src/result_parser.dart.lib.js:187:55)
    at Function.get _platform [as _platform] (http://localhost:60806/store2/packages/flutter_stripe/src/stripe.dart.lib.js:362:110)
    at stripe.Stripe.__._initialise (http://localhost:60806/store2/packages/flutter_stripe/src/stripe.dart.lib.js:377:29)
    at _initialise.next (<anonymous>)
    at runBody (http://localhost:60806/store2/dart_sdk.js:40666:34)`

**Comment by ehcpdeveloper** [comment]
Thanks for the info. it would be nice to have this info (web not supported) in the homepage/readme of the project on a visible location. This "nice to have" is valid for all flutter packages.
