### ISSUE TITLE
CardField won't show in Android, for IOS working fine.

### ISSUE THREAD

**Issue by vignarajj** [flutter-stripe/flutter_stripe#413]
com.test.test_app E/MethodChannel#flutter/platform_views: Failed to handle method call
    java.lang.NullPointerException: Missing required view with ID: com.test.test_app:id/card_brand_view
        at com.stripe.android.databinding.CardInputWidgetBinding.bind(CardInputWidgetBinding.java:163)
        at com.stripe.android.databinding.CardInputWidgetBinding.inflate(CardInputWidgetBinding.java:89)
        at com.stripe.android.view.CardInputWidget.<init>(CardInputWidget.kt:62)
        at com.stripe.android.view.CardInputWidget.<init>(CardInputWidget.kt:56)
        at com.reactnativestripesdk.StripeSdkCardView.<init>(StripeSdkCardView.kt:35)
        at com.reactnativestripesdk.StripeSdkCardViewManager.createViewInstance(StripeSdkCardViewManager.kt:58)
        at com.flutter.stripe.StripeSdkCardPlatformView.<init>(StripeSdkCardPlatformView.kt:33)
        at com.flutter.stripe.StripeSdkCardPlatformViewFactory.create(StripeSdkCardPlatformViewFactory.kt:21)
        at io.flutter.plugin.platform.PlatformViewsController$1.createAndroidViewForPlatformView(PlatformViewsController.java:151)
        at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:104)
        at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:59)
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
        at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:84)
        at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:865)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:335)
        at android.os.Looper.loop(Looper.java:183)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**flutter code:**

```
void addCard1() async {
  PaymentMethod? _paymentMethod;
  String paymentId = '';
  SetupIntent? _paymentIntent;
  CardFieldInputDetails? _cardInfo;
  bool isProgress = false;

  showDialog(
      context: context,
      barrierDismissible: true,
      builder: (BuildContext context) {
        return StatefulBuilder(builder: (BuildContext context, void Function(void Function()) setState) {
          return AlertDialog(
            shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.all(Radius.circular(2.0))),
            content: isProgress?
            Container(
              width: ScreenConfig.screenWidth - 300,
              height: 300,
              child: Center(
                child: CircularProgressIndicator(color: AppTheme.baseColor,),
              ),
            ):
            Column(
              mainAxisSize: MainAxisSize.min,
              children: [
                Text('CARD DETAILS',
                    style:
                    AppTheme.textTheme.headline4!.copyWith(fontSize: 16.0)),
                SizedBox(
                  height: 30,
                ),
                CardField(
                  cvcHintText: 'CVV',
                  numberHintText: '1234',
                  expirationHintText: 'MM/YYYY',
                  onCardChanged: (res) {
                    setState(() {
                      _cardInfo = res;
                    });
                  },
                ),
                SizedBox(
                  height: 30,
                ),
                FlatButtonCustom(() async {
                  if (_cardInfo == null || _cardInfo?.complete == false) {
                    showToast("Fill all details");
                    return;
                  }

                  setState(() {
                    isProgress = true;
                  });

                  await Stripe.instance
                      .confirmSetupIntent(
                      clientSecret, PaymentMethodParams.card())
                      .then((result) {
                    setState(() {
                      _paymentIntent = result;
                      paymentId = result.paymentMethodId;
                    });
                    print("_status ${_paymentIntent!.status}");
                    if (_paymentIntent!.status.toLowerCase() == 'succeeded') {
                      setState(() {
                        isProgress = false;
                      });
                      Navigator.of(context).pop();
                    } else if (_paymentIntent!.status.toLowerCase() == 'failed') {
                      print("payment failed");
                      setState(() {
                        isProgress = false;
                      });
                      Navigator.of(context).pop();
                    } else if (_paymentIntent!.status.toLowerCase() == 'cancelled') {
                      print("payment cancelled");
                      setState(() {
                        isProgress = false;
                      });
                    } else {
                      print("payment cancelled other reason");
                      setState(() {
                        isProgress = false;
                      });
                    }
                  }).catchError((e){
                    print('paymentError ${e.toString()}');
                    setState((){
                      isProgress = false;
                    });
                  });
                }, 'SAVE', false)
              ],
            ),
          );
        },);
      });
}
```

**build.gradle:**
```
buildscript {
    ext.kotlin_version = '1.5.0'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.10'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

**styles.xml:**

```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <!-- Theme applied to the Android Window while the process is starting -->
    <style name="LaunchTheme" parent="Theme.AppCompat.Light.NoActionBar">
        <!-- Show a splash screen on the activity. Automatically removed when
             Flutter draws its first frame -->
        <item name="android:windowBackground">@drawable/launch_background</item>
    </style>
    <!-- Theme applied to the Android Window as soon as the process has started.
         This theme determines the color of the Android Window while your
         Flutter UI initializes, as well as behind your Flutter UI while its
         running.

         This Theme is only used starting with V2 of Flutter's Android embedding. -->
    <style name="NormalTheme" parent="Theme.MaterialComponents">
        <item name="android:windowBackground">?android:colorBackground</item>
    </style>
    <style name="FullScreenDialogStyle" parent="Theme.AppCompat.Dialog">
      <item name="android:windowNoTitle">true</item>
      <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
      <item name="colorPrimary">@color/colorPrimary</item>

      <!-- Set this to true if you want Full Screen without status bar -->
      <item name="android:windowFullscreen">false</item>

      <item name="android:windowIsFloating">false</item>

      <!-- This is important! Don't forget to set window background -->
      <item name="android:windowBackground">@color/colorWhite</item>

      <!-- Additionally if you want animations when dialog opening -->
      <item name="android:windowEnterAnimation">@anim/slide_up</item>
      <item name="android:windowExitAnimation">@anim/slide_down</item>
  </style>
</resources>

```

**To Reproduce**
Instance happens when trying to save the card for future use, these error occurs. I put the card inside the showDialog. When dialog showing, I got this issue. 

**Smartphone / tablet**
 - Device: Nexus 5x (Emulator)
 - OS: Android 11
 - Kotlin version: 1.5.0
 - Gradle version: 4.1.2

Can you please help, how to sort out this issue. As per your recent doc, already updated the gradle and styles.xml. But it won't be working in android.

**Comment by remonh87** [comment]
The error you shared has to do with the fact the native view Android view cannot be found. Can you try to not show the field in a dialog?  Also which version of the lib are you using?

**Comment by remonh87** [comment]
Closed due to no response feel free to reopen with the supplied info and we can help out.
