### ISSUE TITLE
google Pay - java.lang.IllegalStateException: Reply already submitted

### ISSUE THREAD

**Issue by Solutionstbd** [flutter-stripe/flutter_stripe#465]
**Describe the bug**
Initiating Google pay using 'Stripe.instance.initGooglePay' and 'Stripe.instance.presentGooglePay' seems to produce 'java.lang.IllegalStateException: Reply already submitted' error.'

I am not certain this is a flutter_stripe package issue, but am hoping someone has come across this before.

This is failing on both the emulator and physical phone with the same error. The last line in the error states the device does not have google pay available and that is false. 

**The Full Error from the debug console**
```
W/System.err( 7051): java.lang.IllegalStateException: Reply already submitted
W/System.err( 7051): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:164)
W/System.err( 7051): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:238)
W/System.err( 7051): 	at com.facebook.react.bridge.Promise$1.run(Promise.java:26)
W/System.err( 7051): 	at android.os.Handler.handleCallback(Handler.java:873)
W/System.err( 7051): 	at android.os.Handler.dispatchMessage(Handler.java:99)
W/System.err( 7051): 	at android.os.Looper.loop(Looper.java:193)
W/System.err( 7051): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
W/System.err( 7051): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err( 7051): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
W/System.err( 7051): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
I/flutter ( 7051): StripeException(error: LocalizedErrorMessage(code: FailureCode.Failed, localizedMessage: presentForPaymentIntent() may only be called when Google Pay is available on this device., message: presentForPaymentIntent() may only be called when Google Pay is available on this device., stripeErrorCode: null, declineCode: null, type: null))
```

**Expected behavior**
Previously the google payment screen would appear with no issue.

**Smartphone / tablet**
 - Device: Android (emulator and physical)
 - OS:  Android 
 - Flutter_Stripe version: [e.g. 2.0.1]
 - Flutter version [e.g. 2.12.0.]

I have made sure my android style is of 'AppCompat'
``` xml
    <style name="NormalTheme" parent="Theme.AppCompat.Light.NoActionBar">
        <item name="android:windowBackground">?android:colorBackground</item>
        <item name="android:defaultFocusHighlightEnabled">false</item>
    </style>
```

And my MainActivity.kt utilizes 'FlutterFragmentActivity'

**Comment by Solutionstbd** [comment]
I was able to reproduce the problem within the example app my adding the following package to pubspec.yaml
```
cloud_functions: ^3.1.0
```

I assume the stripe_flutter package will have to be updated in order to correct this. 

I am not sure how to correct this on my own but will continue digging.

**Comment by jonasbark** [comment]
As you mentioned that it works fine on the example app: Can you provide a reproducible scenario?

**Comment by Solutionstbd** [comment]
Downloaded the example app and started fresh. Followed the screen to the wallets->googlePay(Android) and clicked the pay button. The google pay sheet appeared and now error in the debug log found. Looks clean.

I added the cloud_function package as mentioned above and the following error appears
```

W/System.err( 6837): java.lang.IllegalStateException: Reply already submitted
W/System.err( 6837): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:164)
W/System.err( 6837): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:238)
W/System.err( 6837): 	at com.facebook.react.bridge.Promise$1.run(Promise.java:26)
W/System.err( 6837): 	at android.os.Handler.handleCallback(Handler.java:883)
W/System.err( 6837): 	at android.os.Handler.dispatchMessage(Handler.java:100)
W/System.err( 6837): 	at android.os.Looper.loop(Looper.java:241)
W/System.err( 6837): 	at android.app.ActivityThread.main(ActivityThread.java:7582)
W/System.err( 6837): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err( 6837): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
W/System.err( 6837): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
W/ActivityThread( 6837): handleWindowVisibility: no activity for token android.os.BinderProxy@ab7c164
```

The google sheet still appeared as expected, so I am working on finding a way to reproduce the additional problem of the google sheet not appearing. Will post once something is found.

**Comment by Solutionstbd** [comment]
I have not been able to reproduce the issue where where the google pay can not appear within the example app. Also the issue disappeared on my production app later today. No code has changed.
The Illegal state exception still exists but I do not think it is the same the issue as what was causing the google pay connection issue.
Since the main reason for my opening of this issue has disappeared, I'm closing the issue.
