### ISSUE TITLE
[web] I encounter an error about size or something.

### ISSUE THREAD

**Issue by NaokiDohi** [flutter-stripe/flutter_stripe#493]
When I wrote like below,
```
import 'package:flutter/material.dart';
import 'package:flutter_stripe_web/flutter_stripe_web.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    CardEditController? _cardEditController = CardEditController();
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: SizedBox(
        height: MediaQuery.of(context).size.height,
        width: MediaQuery.of(context).size.width,
        child: WebCardField(
          controller: _cardEditController,
        ),
      ),
    );
  }
}
```
I get the error below.
```
Error: Assertion failed:
../…/widgets/framework.dart:2577
_debugCurrentBuildTarget == context
is not true
    at Object.throw_ [as throw] (http://localhost:56021/dart_sdk.js:5061:11)
    at Object.assertFailed (http://localhost:56021/dart_sdk.js:4986:15)
at http://localhost:56021/packages/flutter/src/widgets/widget_inspector.dart.lib.js:44225:81
at framework.BuildOwner.new.buildScope (http://localhost:56021/packages/flutter/src/widgets/widget_inspector.dart.lib.js:44229:32)
at RenderObjectToWidgetAdapter.new.attachToRenderTree (http://localhost:56021/packages/flutter/src/widgets/widget_inspector.dart.lib.js:46901:17)
at binding$5.WidgetsFlutterBinding.new.attachRootWidget (http://localhost:56021/packages/flutter/src/widgets/widget_inspector.dart.lib.js:46771:236)
at http://localhost:56021/packages/flutter/src/widgets/widget_inspector.dart.lib.js:46765:14
    at internalCallback (http://localhost:56021/dart_sdk.js:25436:11)
```
this is my dependencies.
```
dependencies:
  flutter:
    sdk: flutter
  flutter_stripe: ^2.1.0
  flutter_stripe_web: ^0.1.0
  cupertino_icons: ^1.0.2
```
I added a Sized box. But I can't solve it.
How to fix it?

**Comment by jamesblasco** [comment]
This is not related to this plugin and more understanding `BuildContext`. You are trying to access `MediaQuery.of(context)` using a context reference where there is no MediaQuery.

Notice the root MediaQuery value is added by the MaterialApp, so you would need to use a context that has MaterialApp as an ancestor.

```
class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    CardEditController? _cardEditController = CardEditController();
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Builder(
        builder: (context) {
          return SizedBox(
            height: MediaQuery.of(context).size.height,
            width: MediaQuery.of(context).size.width,
            child: WebCardField(
              controller: _cardEditController,
            ),
          );
        },
      ),
    );
  }
}
````

Several things about this:
1. Why you want a CardField that is the full size of the screen?
2.  Consider using `CardField` from the flutter_stripe package even for web, it should work.
