### ISSUE TITLE
Error: Unsupported operation: Platform._operatingSystem (Flutter web, version 2.1.0)

### ISSUE THREAD

**Issue by bizz84** [flutter-stripe/flutter_stripe#495]
**Describe the bug**
According to the changelog for [version 2.1.0](https://pub.dev/packages/flutter_stripe/changelog#210), web support is now available in beta.
But when I run my app, I get an error as soon as I try to set the `publishableKey`:

```dart
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  // Stripe setup
  Stripe.publishableKey = '<my-public-key>';
  Stripe.merchantIdentifier = 'merchant.flutter.stripe.test';
  Stripe.urlScheme = 'flutterstripe';
  await Stripe.instance.applySettings();

  runApp(MyApp());
}
```

I have already followed the steps [on this page](https://github.com/flutter-stripe/flutter_stripe/tree/main/packages/stripe_web) and added `<script src="https://js.stripe.com/v3/"></script>` inside the `<body>`.

Am I missing something?

**To Reproduce**
Start any app with Flutter web and set `Stripe.publishableKey` inside `main()`.
The app will immediately throw the error log below.

**Expected behavior**
The app starts regularly.

**Smartphone / tablet**
 - Device: Chrome Version 96.0.4664.110 
 - OS: macOS BigSur 11.6
 - Package version: 2.1.0
 - Flutter version 2.8.0

**Additional context**
Here's the error log:

```
╔════════════════════════════════════════════════════════════════════════════╗
║ A new version of Flutter is available!                                     ║
║                                                                            ║
║ To update to the latest version, run "flutter upgrade".                    ║
╚════════════════════════════════════════════════════════════════════════════╝
Launching lib/main_development.dart on Chrome in debug mode...
This app is linked to the debug service: ws://127.0.0.1:63878/M2VWG1YTAIc%3D/ws
Debug service listening on ws://127.0.0.1:63878/M2VWG1YTAIc=/ws
💪 Running with sound null safety 💪
Connecting to VM Service at ws://127.0.0.1:63878/M2VWG1YTAIc=/ws
Error: Unsupported operation: Platform._operatingSystem
    at Object.throw_ [as throw] (http://localhost:63812/dart_sdk.js:5063:11)
    at Function._operatingSystem (http://localhost:63812/dart_sdk.js:57126:17)
    at Function.get operatingSystem [as operatingSystem] (http://localhost:63812/dart_sdk.js:57172:27)
    at get _operatingSystem (http://localhost:63812/dart_sdk.js:57085:27)
    at Function.desc.get [as _operatingSystem] (http://localhost:63812/dart_sdk.js:5556:17)
    at get isIOS (http://localhost:63812/dart_sdk.js:57109:26)
    at Function.desc.get [as isIOS] (http://localhost:63812/dart_sdk.js:5556:17)
at MethodChannelStripeFactory.create (http://localhost:63812/packages/stripe_platform_interface/src/result_parser.dart.lib.js:896:122)
at get _instance (http://localhost:63812/packages/stripe_platform_interface/src/result_parser.dart.lib.js:684:30)
    at Function.desc.get [as _instance] (http://localhost:63812/dart_sdk.js:5556:17)
at Function.get instance [as instance] (http://localhost:63812/packages/stripe_platform_interface/src/result_parser.dart.lib.js:629:55)
at Function.get _platform [as _platform] (http://localhost:63812/packages/flutter_stripe/src/stripe.dart.lib.js:343:110)
at stripe.Stripe.__.markNeedsSettings (http://localhost:63812/packages/flutter_stripe/src/stripe.dart.lib.js:348:26)
at Function.set publishableKey [as publishableKey] (http://localhost:63812/packages/flutter_stripe/src/stripe.dart.lib.js:65:30)
at main (http://localhost:63812/packages/my_shop_ecommerce_flutter/main_development.dart.lib.js:48:38)
    at main.next (<anonymous>)
    at http://localhost:63812/dart_sdk.js:40192:33
    at _RootZone.runUnary (http://localhost:63812/dart_sdk.js:40062:59)
    at _FutureListener.thenAwait.handleValue (http://localhost:63812/dart_sdk.js:34983:29)
    at handleValueCallback (http://localhost:63812/dart_sdk.js:35551:49)
    at Function._propagateToListeners (http://localhost:63812/dart_sdk.js:35589:17)
    at _Future.new.[_completeWithValue] (http://localhost:63812/dart_sdk.js:35437:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:63812/dart_sdk.js:35458:35)
    at Object._microtaskLoop (http://localhost:63812/dart_sdk.js:40330:13)
    at _startMicrotaskLoop (http://localhost:63812/dart_sdk.js:40336:13)
    at http://localhost:63812/dart_sdk.js:35811:9
```

**Comment by bizz84** [comment]
Turns out I forgot to add this to my `pubspec.yaml`:

```yaml
  flutter_stripe_web: 0.1.0
```

Maybe this could be included in the documentation?

**Comment by jamesblasco** [comment]
Ahh great you found out the problem!

It is explained in the [`stripe_web` readme](https://github.com/flutter-stripe/flutter_stripe/blob/main/packages/stripe_web/README.md), but maybe I should make it more prominent.

This step will be removed when we launch the web version as stable 👍🏻
