### ISSUE TITLE
Flutter Web : Cannot read properties of undefined (reading 'id')

### ISSUE THREAD

**Issue by shadyaziza** [flutter-stripe/flutter_stripe#600]
Getting this error while trying to run the example in the docs on ** flutter web**

```zsh
TypeError: Cannot read properties of undefined (reading 'id')
               at Object.PaymentMethodParser$124parse [as PaymentMethodParser|parse]
               (http://localhost:44311/packages/flutter_stripe_web/src/widgets/card_field.dart.lib.js:995:64)
               at createCardPaymentMethod (http://localhost:44311/packages/flutter_stripe_web/src/widgets/card_field.dart.lib.js:1077:63)
               at createCardPaymentMethod.next (<anonymous>)
               at http://localhost:44311/dart_sdk.js:40571:33
               at _RootZone.runUnary (http://localhost:44311/dart_sdk.js:40441:59)
               at _FutureListener.thenAwait.handleValue (http://localhost:44311/dart_sdk.js:35363:29)
               at handleValueCallback (http://localhost:44311/dart_sdk.js:35931:49)
               at Function._propagateToListeners (http://localhost:44311/dart_sdk.js:35969:17)
               at _Future.new.[_completeWithValue] (http://localhost:44311/dart_sdk.js:35817:23)
               at async._AsyncCallbackEntry.new.callback (http://localhost:44311/dart_sdk.js:35838:35)
               at Object._microtaskLoop (http://localhost:44311/dart_sdk.js:40708:13)
               at _startMicrotaskLoop (http://localhost:44311/dart_sdk.js:40714:13)
               at http://localhost:44311/dart_sdk.js:36191:9
```

**Steps to reproduce the behavior:**

Run this code and press on `pay` button

```dart
import 'package:flutter/material.dart';
import 'package:flutter_stripe/flutter_stripe.dart';

Future<void> main() async {
 WidgetsFlutterBinding.ensureInitialized();
  Stripe.publishableKey = testKey;
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(),
        body: Column(
          children: [
            CardField(
              onCardChanged: (card) {
                print(card);
              },
            ),
            TextButton(
              onPressed: () async {
                // create payment method
                final paymentMethod = await Stripe.instance
                    .createPaymentMethod(PaymentMethodParams.card());
              },
              child: Text('pay'),
            )
          ],
        ),
      ),
    );
  }
}
```

**Additional context:**

```zsh
[✓] Flutter (Channel stable, 2.10.1, on Manjaro Linux 5.13.19-2-MANJARO, locale ar_EG.UTF-8)
    • Flutter version 2.10.1 at /home/user/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db747aa133 (2 weeks ago), 2022-02-09 13:57:35 -0600
    • Engine revision ab46186b24
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /usr/bin/google-chrome-stable

[✓] VS Code
    • VS Code at /snap/code/current
    • Flutter extension version 3.34.0

[✓] Connected device (1 available)
    • Chrome (web)    • chrome • web-javascript • Google Chrome 96.0.4664.93

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

.

**Comment by remonh87** [comment]
It looks like your payment method is incorrect, I am able to create the payment method without issues. Did you follow the instructions described on: https://github.com/flutter-stripe/flutter_stripe/tree/main/packages/stripe_web ?

**Comment by shadyaziza** [comment]
Yes, but I just figured out that I was trying to invoke the `createPaymentMethod` without adding information in the card and expecting something to happen. I guess populating the card is somehow linked to the stripe api.
