### ISSUE TITLE
Missing API keys in the Authorization header

### ISSUE THREAD

**Issue by kekko7072** [flutter-stripe/flutter_stripe#63]
In my flutter app I added the public key, in the serverI added my dev keys In the `server.env.example` file of the server but when I try the server returns this error. 

```
UnhandledPromiseRejectionWarning: Error: You did not provide an API key. You need to provide your API key in the Authorization header, using Bearer auth (e.g. 'Authorization: Bearer YOUR_SECRET_KEY'). See https://stripe.com/docs/api#authentication for details, or we can help at https://support.stripe.com/.
    at IncomingMessage.<anonymous> (/Users/francescovezzani/Developer/TheLounge/App/the_lounge/server/node_modules/stripe/lib/StripeResource.js:174:21)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
    at IncomingMessage.EventEmitter.emit (domain.js:467:12)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(node:13928) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)

```
Am I missing configuration, where I need to add the secret key?

**Comment by thorsten-stripe** [comment]
Did you copy the example file to `server/.env` before adding it as outlined in the README? https://github.com/flutter-stripe/flutter_stripe#run-the-example-app

**Comment by kekko7072** [comment]
yeah I didnt `cp server/.env.example server/.env` sorry guys now it works
