### ISSUE TITLE
Unhandled Exception: Looking up a deactivated widget's ancestor is unsafe.

### ISSUE THREAD

**Issue by jaumard** [flutter-stripe/flutter_stripe#658]
**Describe the bug**
Getting a crash when going back from stripe on Android. 
I want to redirect to success or canceled screen when going back from stripe. So here is my code:

```
ElevatedButton(
                      onPressed: () async {
                        final userStore = ref.read(userStoreProvider);
                        final success = await showLoadingDialog(context, (_) => Text(context.l10n.loading), () async {
                          await store.loadPaymentSessionId(e, userStore.user?.email);
                        });
                        if (success) {
                          final result = await redirectToCheckout(
                            context: context,
                            sessionId: store.sessionId,
                            publishableKey: kIsProductionMode ? kStripeProdKey : kStripeTestKey,
                            successUrl: Config().baseUrl + '/${DonateSuccess.name}',
                            canceledUrl: Config().baseUrl + '/${DonateCancelled.name}',
                          );
                          result.when(
                            redirected: () {},
                            success: () {
                              context.goNamed(DonateSuccess.name);
                            },
                            canceled: () {
                              context.goNamed(DonateCancelled.name);
                            },
                            error: (error) {
                              showErrorDialog(context, error, StackTrace.current);
                            },
                          );
                        }
                      },
                      child: Padding(
                        padding: const EdgeInsets.all(kNormalPadding),
                        child: Text('${(e.price / 100).toStringAsFixed(0)} ${e.currency.toUpperCase()}'),
                      ),
                    ),
)
```

Here is the log I get:

```
E/flutter (11109): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Looking up a deactivated widget's ancestor is unsafe.
E/flutter (11109): At this point the state of the widget's element tree is no longer stable.
E/flutter (11109): To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by calling dependOnInheritedWidgetOfExactType() in the widget's didChangeDependencies() method.
E/flutter (11109): #0      Element._debugCheckStateIsActiveForAncestorLookup.<anonymous closure> (package:flutter/src/widgets/framework.dart:4153:9)
E/flutter (11109): #1      Element._debugCheckStateIsActiveForAncestorLookup (package:flutter/src/widgets/framework.dart:4167:6)
E/flutter (11109): #2      Element.dependOnInheritedWidgetOfExactType (package:flutter/src/widgets/framework.dart:4182:12)
E/flutter (11109): #3      HookElement.dependOnInheritedWidgetOfExactType (package:flutter_hooks/src/framework.dart:482:18)
E/flutter (11109): #4      GoRouter.of (package:go_router/src/go_router.dart:136:17)
E/flutter (11109): #5      GoRouterHelper.goNamed (package:go_router/go_router.dart:46:16)
E/flutter (11109): #6      DonateByCard.build.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:heal_happy/donations/donate.dart:230:39)
E/flutter (11109): #7      _$_Canceled.when (package:stripe_checkout/src/platforms/checkout.freezed.dart:439:20)
E/flutter (11109): #8      DonateByCard.build.<anonymous closure>.<anonymous closure> (package:heal_happy/donations/donate.dart:224:34)
```

So look like the context inside the `when` isn't valid anymore and I can't redirect to cancel or success page.  Any idea how can I fix this?

**Comment by remonh87** [comment]
I think the widget is still building when you execute a navigator callback. This is indeed not safe. you can either use 
```dart
WidgetsBinding.instance!.addPostFrameCallback((_) {
  // executes after build
})
```

or look for a solution in the state management package (e.g. bloc listener, Riverpod listen etc).

**Comment by jaumard** [comment]
In fact I already tried this solution and wrap the `when` inside the `addPostFrameCallback ` but it doesn't work either.

**Comment by remonh87** [comment]
hmm maybe it has to do with the fact that you use outdated context? What if you inject a function in your widget that does the navigation? 

```dart
class FooWidget extends StatelessWidget{ 

const FooWidget({
   required this.navigateTo, Key? key)}: super(key: key);

final ValueChanged<String> navigateTo;
}
```

Also I assume the ElevatedButton is in the build method?

**Comment by jaumard** [comment]
You were right the context was outdated even if the dialog was still on the screen, I had to inject function all the way up to where the dialog was open to have the screen context instead of dialog context. Thanks for your help!
