### ISSUE TITLE
Undefined behavior (app crash) with Google Pay on Android

### ISSUE THREAD

**Issue by anmentone** [flutter-stripe/flutter_stripe#72]
When using the GooglePayButton widget I get strange behavior if I decide to cancel the payment by closing the open modal after pressing the pay button. 

**To reproduce on example app**
I wanted to make a video demonstration but unfortunately, the google play screen is obscured (obviously) with any screen capture. 
The steps are pretty simple:
1. On the example App, choose **Google Pay payment (Android)**
2. Then press the pay button
3. Close the Google Pay screen, without making any payment. I've tried the X in the top right corner and the back button on the navigation bar of my Huawei phone and the app crashes trying to close the screen.

The error messages seem to be clear, I'm trying to take a deeper look.
<details>
<summary>log: RuntimeException</summary>

```
D/AndroidRuntime(19083): Shutting down VM
I/QarthLog(19083): [PatchStore] createDisableExceptionQarthFile
I/QarthLog(19083): [PatchStore] create disable file for com.flutter_stripe.example uid is 10473
E/AndroidRuntime(19083): FATAL EXCEPTION: main
E/AndroidRuntime(19083): Process: com.flutter_stripe.example, PID: 19083
E/AndroidRuntime(19083): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=991, result=0, data=null} to activity {com.flutter_stripe.example/com.flutter_stripe.example.MainActivity}: java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter data
E/AndroidRuntime(19083): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5471)
E/AndroidRuntime(19083): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5512)
E/AndroidRuntime(19083): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
E/AndroidRuntime(19083): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
E/AndroidRuntime(19083): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
E/AndroidRuntime(19083): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2386)
E/AndroidRuntime(19083): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(19083): 	at android.os.Looper.loop(Looper.java:213)
E/AndroidRuntime(19083): 	at android.app.ActivityThread.main(ActivityThread.java:8178)
E/AndroidRuntime(19083): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(19083): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
E/AndroidRuntime(19083): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
E/AndroidRuntime(19083): Caused by: java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter data
E/AndroidRuntime(19083): 	at com.reactnativestripesdk.StripeSdkModule$mActivityEventListener$1.onActivityResult(Unknown Source:7)
E/AndroidRuntime(19083): 	at com.facebook.react.bridge.BaseActivityEventListener.onActivityResult(BaseActivityEventListener.kt:15)
E/AndroidRuntime(19083): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistry.java:739)
E/AndroidRuntime(19083): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:426)
E/AndroidRuntime(19083): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:677)
E/AndroidRuntime(19083): 	at io.flutter.embedding.android.FlutterFragment.onActivityResult(FlutterFragment.java:769)
E/AndroidRuntime(19083): 	at io.flutter.embedding.android.FlutterFragmentActivity.onActivityResult(FlutterFragmentActivity.java:509)
E/AndroidRuntime(19083): 	at android.app.Activity.dispatchActivityResult(Activity.java:8413)
E/AndroidRuntime(19083): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5464)
E/AndroidRuntime(19083): 	... 11 more
I/Process (19083): Sending signal. PID: 19083 SIG: 9
Lost connection to device.
Exited (sigterm)
```
</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.2.0, on Linux, locale en_GB.UTF-8)
    • Flutter version 2.2.0 at /home/anmentone/lib/flutter
    • Framework revision b22742018b (10 days ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/anmentone/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /usr/local/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /usr/local/android-studio
    • Flutter plugin version 56.0.2
    • Dart plugin version 202.8488
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)

[✓] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at /usr/local/idea-IC-211.7142.45
    • Flutter plugin version 56.0.5
    • Dart plugin version 211.7233

[✓] VS Code (version 1.56.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.22.0

[✓] Connected device (2 available)
    • POT LX1 (mobile) • 39V4C19A18025168 • android-arm64  • Android 10 (API 29)
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 90.0.4430.212

• No issues found!
```
</details>
Flutter version 1.0.1+2

**Comment by jamesblasco** [comment]
Thank you for submitting the issue. It will be fixed in the upcoming release 🙂
