### ISSUE TITLE
Error during initialize library

### ISSUE THREAD

**Issue by AnnaVadimovna** [flutter-stripe/flutter_stripe#729]
App crash during app initializing with error on few devices

```
Unable to start activity ComponentInfo{MainActivity}: androidx.fragment.app.L: 
Unable to instantiate fragment PaymentLauncherFragment: could not find Fragment constructor
```

 - Device: Galaxy S20 FE 5G, Galaxy A40, Redmi Note 8T
 - OS: android 9+
 - Package version: [2.4.0]
 - Flutter version [e.g. 2.0.0.]

Fragments need to have a no-args constructor for the Android system to re-instantiate them.
https://developer.android.com/reference/android/app/Fragment#public-constructors_1

**Comment by jonasbark** [comment]
Can you post the full stack trace of the exception?
Also please provide the information about the package version and Flutter version that you use.

**Comment by AnnaVadimovna** [comment]
Crash report from Crashlutics
i.o.i0 is PaymentLauncherFragment

```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{MainActivity}: androidx.fragment.app.L: Unable to instantiate fragment i.o.i0: could not find Fragment constructor
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3472)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3636)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2084)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7888)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:981)

Caused by androidx.fragment.app.L: Unable to instantiate fragment i.o.i0: could not find Fragment constructor
       at androidx.fragment.app.Fragment.instantiate(Fragment.java:66)
       at androidx.fragment.app.FragmentContainer.instantiate(FragmentContainer.java:0)       at androidx.fragment.app.FragmentManager$2.instantiate(FragmentManager.java:0)
       at androidx.fragment.app.FragmentState.instantiate(FragmentState.java:0)       at androidx.fragment.app.FragmentStateManager.<init>(FragmentStateManager.java:0)
       at androidx.fragment.app.FragmentManager.J0(FragmentManager.java:123)
       at androidx.fragment.app.FragmentManager.attachController(FragmentManager.java:0)
       at androidx.fragment.app.FragmentController.attachHost(FragmentController.java:5)
       at androidx.fragment.app.FragmentActivity.lambda$init$1(FragmentActivity.java:0)       at androidx.fragment.app.FragmentActivity.lambda$init$1$FragmentActivity(FragmentActivity.java:0)       at androidx.fragment.app.-$$Lambda$FragmentActivity$QtiQ2ZI3e38UkO1_xuJ8vE_JZj4.onContextAvailable(-.java:0)
       at androidx.activity.contextaware.ContextAwareHelper.dispatchOnContextAvailable(ContextAwareHelper.java:20)
       at androidx.activity.ComponentActivity.onCreate(ComponentActivity.java:7)
       at androidx.fragment.app.FragmentActivity.onCreate()
       at io.flutter.embedding.android.FlutterFragmentActivity.onCreate(FlutterFragmentActivity.java:0)
       at android.app.Activity.performCreate(Activity.java:8019)
       at android.app.Activity.performCreate(Activity.java:8003)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1310)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3445)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3636)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2084)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7888)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:981)

Caused by java.lang.NoSuchMethodException: i.o.i0.<init> []
       at java.lang.Class.getConstructor0(Class.java:2332)
       at java.lang.Class.getConstructor(Class.java:1728)
       at androidx.fragment.app.Fragment.instantiate(Fragment.java:15)
       at androidx.fragment.app.FragmentContainer.instantiate(FragmentContainer.java:0)       at androidx.fragment.app.FragmentManager$2.instantiate(FragmentManager.java:0)
       at androidx.fragment.app.FragmentState.instantiate(FragmentState.java:0)       at androidx.fragment.app.FragmentStateManager.<init>(FragmentStateManager.java:0)
       at androidx.fragment.app.FragmentManager.J0(FragmentManager.java:123)
       at androidx.fragment.app.FragmentManager.attachController(FragmentManager.java:0)
       at androidx.fragment.app.FragmentController.attachHost(FragmentController.java:5)
       at androidx.fragment.app.FragmentActivity.lambda$init$1(FragmentActivity.java:0)       at androidx.fragment.app.FragmentActivity.lambda$init$1$FragmentActivity(FragmentActivity.java:0)       at androidx.fragment.app.-$$Lambda$FragmentActivity$QtiQ2ZI3e38UkO1_xuJ8vE_JZj4.onContextAvailable(-.java:0)
       at androidx.activity.contextaware.ContextAwareHelper.dispatchOnContextAvailable(ContextAwareHelper.java:20)
       at androidx.activity.ComponentActivity.onCreate(ComponentActivity.java:7)
       at androidx.fragment.app.FragmentActivity.onCreate()
       at io.flutter.embedding.android.FlutterFragmentActivity.onCreate(FlutterFragmentActivity.java:0)
       at android.app.Activity.performCreate(Activity.java:8019)
       at android.app.Activity.performCreate(Activity.java:8003)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1310)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3445)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3636)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2084)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7888)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:981)
```

Package version: 2.4.0
Flutter version 2.10.5

**Comment by jonasbark** [comment]
I don't see anything that suggests that it's caused by Stripe - do you?
Can you update to the latest Flutter + stripe version and check again?

**Comment by AnnaVadimovna** [comment]
Now checked with the flag "Don’t Keep Activities". The bug began to be reproduced when the application was restored from the background. This behavior can also happen if the system decides to recreate our activity after launching another application.

This is why fragments are required to have an empty constructor.

**Comment by huckle-panda** [comment]
Relates to this issue in the underlying dependency:  https://github.com/stripe/stripe-react-native/issues/930

**Comment by jonasbark** [comment]
Thanks for cross-linking 👍

**Comment by RafaRuiz** [comment]
By the way, a quick workaround (only if you don't need that wild Fragment around) is doing this on Android:

- Create a Method Channel to talk through the native bridge
- Create a method, for example `"removeStripeFragmentOnTop"`

```
    new MethodChannel(flutterEngine.getDartExecutor().getBinaryMessenger(), CHANNEL)
            .setMethodCallHandler(
                    (call, result) -> {
                        if (call.method.equals("removeStripeFragmentOnTop")) {
                            // TODO - temporary, see [https://github.com/stripe/stripe-react-native/issues/930]
                            final Fragment possibleStripeFragment = getSupportFragmentManager().findFragmentByTag("payment_launcher_fragment");
                            if (possibleStripeFragment != null) {
                                getSupportFragmentManager().beginTransaction().remove(possibleStripeFragment).commitAllowingStateLoss();
                            }
                            result.success(true);
                        } else {
                            result.notImplemented();
                        }
                    }
            );
```

Then call it from Flutter (right after initialising Stripe, after its `Future`)

**Comment by remonh87** [comment]
This is fixed  and should not happen anymore (tried to reproduce it). If the issue still happens create a new ticket or reopen this one and we will contact stripe
