### ISSUE TITLE
App crash on Setup Future Payment example

### ISSUE THREAD

**Issue by giandifra** [flutter-stripe/flutter_stripe#85]
**Describe the bug**
Hi, I'm trying setup_future_payment example but there is an exception from native Android code. 
The error is generated by `retrievePaymentIntent` method

```
E/AndroidRuntime( 6283): FATAL EXCEPTION: AsyncTask #2
E/AndroidRuntime( 6283): Process:  PID: 6283
E/AndroidRuntime( 6283): java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: AsyncTask #2
E/AndroidRuntime( 6283): 	at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:1230)
E/AndroidRuntime( 6283): 	at io.flutter.embedding.engine.FlutterJNI.invokePlatformMessageResponseCallback(FlutterJNI.java:905)
E/AndroidRuntime( 6283): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:160)
E/AndroidRuntime( 6283): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:238)
E/AndroidRuntime( 6283): 	at com.facebook.react.bridge.Promise.resolve(Promise.java:17)
E/AndroidRuntime( 6283): 	at com.reactnativestripesdk.StripeSdkModule.retrievePaymentIntent$lambda-7(StripeSdkModule.kt:418)
E/AndroidRuntime( 6283): 	at com.reactnativestripesdk.StripeSdkModule.lambda$IKcyWuzmECIpax6mKWLUzTGJuho(Unknown Source:0)
E/AndroidRuntime( 6283): 	at com.reactnativestripesdk.-$$Lambda$StripeSdkModule$IKcyWuzmECIpax6mKWLUzTGJuho.run(Unknown Source:6)
E/AndroidRuntime( 6283): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
E/AndroidRuntime( 6283): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime( 6283): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime( 6283): 	at java.lang.Thread.run(Thread.java:923)
I/Process ( 6283): Sending signal. PID: 6283 SIG: 9
```

**Comment by jonasbark** [comment]
I can't reproduce this locally - which Android version are you using?

**Comment by giandifra** [comment]
compileSdkVersion 29
minSdkVersion 21
targetSdkVersion 29

**Comment by jonasbark** [comment]
I actually meant Android version of your test device

**Comment by giandifra** [comment]
Oh sorry, I'm testing on Android 11

**Comment by jonasbark** [comment]
Can you try the following:
1. open the Android part of your Flutter project in Android Studio 
2. find Result.java file from stripe_android
3. Replace with https://gist.github.com/jonasbark/0755416627358059458c5aa487451f76 
4. Compile again and try again

**Comment by giandifra** [comment]
Now it works. I have other exception on `confirmPaymentMethod` , I will investigate more and i will open a new issue if i need

Thanks
