### ISSUE TITLE
Displaying a CardField on flutter web

### ISSUE THREAD

**Issue by Quesadeha** [flutter-stripe/flutter_stripe#865]
**Describe the bug**
I have been trying to replicate the Webhook Payment Screen from the example folder. I think I may be missing something, but displaying the CardField on ios and android works as expected but displays as a blank line on web with the error "bad state: source maps are not done downloading". I have the flutter_stripe and flutter_stripe_web packages installed. 
**To Reproduce**
Run this on web. 
```
import 'package:flutter/material.dart';
import 'package:flutter_stripe/flutter_stripe.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  MyAppState createState() => MyAppState();
}

class MyAppState extends State<MyApp> {
  CardFieldInputDetails? _card;
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Test',
      home: Scaffold(
        body: Column(
          children: [
            CardField(
              cursorColor: Colors.black,
              enablePostalCode: true,
              countryCode: 'US',
              postalCodeHintText: 'Enter the us postal code',
              onCardChanged: (card) {
                setState(() {
                  _card = card;
                });
              },
            ),
          ],
        ),
      ),
    );
  }
}
```

**Expected behavior**
I'd expect the card field to show up as an editable field like ios and android, but instead throws an error and is just a blank line.

**Versions**
  flutter_stripe: ^4.0.0
  flutter_stripe_web: ^1.2.0

**Output**
```
Height of Platform View type: [stripe_card] may not be set. Defaulting to `height: 100%`.
Set `style.height` to any appropriate value to stop this message.
Width of Platform View type: [stripe_card] may not be set. Defaulting to `width: 100%`.
Set `style.width` to any appropriate value to stop this message.
Bad state: Source maps are not done loading.
    at Object.a (http://localhost:60428/stack_trace_mapper.js:295:3)
    at cH.kB (http://localhost:60428/stack_trace_mapper.js:2611:23)
    at Object.j3 (http://localhost:60428/stack_trace_mapper.js:247:69)
    at jT (http://localhost:60428/stack_trace_mapper.js:2630:10)
    at http://localhost:60428/stack_trace_mapper.js:2624:42
    at dart._StackTrace.new.toString (http://localhost:60428/dart_sdk.js:7814:19)
    at Object.str (http://localhost:60428/dart_sdk.js:5497:32)
    at DiagnosticsStackTrace._applyStackFilter (http://localhost:60428/packages/flutter/src/foundation/debug.dart.lib.js:3842:32)
    at new assertions.DiagnosticsStackTrace.new (http://localhost:60428/packages/flutter/src/foundation/debug.dart.lib.js:3855:135)
    at assertions.FlutterErrorDetails.new.debugFillProperties (http://localhost:60428/packages/flutter/src/foundation/debug.dart.lib.js:3553:24)
    at http://localhost:60428/packages/flutter/src/foundation/debug.dart.lib.js:2597:26
    at get builder (http://localhost:60428/packages/flutter/src/foundation/debug.dart.lib.js:2600:30)
    at get builder [as builder] (http://localhost:60428/packages/flutter/src/foundation/debug.dart.lib.js:3880:27)
    at assertions._FlutterErrorDetailsNode.new.getProperties (http://localhost:60428/packages/flutter/src/foundation/debug.dart.lib.js:2612:71)
    at [_debugRender] (http://localhost:60428/packages/flutter/src/foundation/debug.dart.lib.js:1256:37)
    at diagnostics$.TextTreeRenderer.new.render (http://localhost:60428/packages/flutter/src/foundation/debug.dart.lib.js:1170:34)
    at dumpErrorToConsole (http://localhost:60428/packages/flutter/src/foundation/debug.dart.lib.js:3670:128)
    at FlutterError.reportError (http://localhost:60428/packages/flutter/src/foundation/debug.dart.lib.js:3765:27)
    at [_invokeFrameCallback] (http://localhost:60428/packages/flutter/src/scheduler/binding.dart.lib.js:741:35)
    at binding$5.WidgetsFlutterBinding.new.handleDrawFrame (http://localhost:60428/packages/flutter/src/scheduler/binding.dart.lib.js:712:37)
    at [_handleDrawFrame] (http://localhost:60428/packages/flutter/src/scheduler/binding.dart.lib.js:660:12)
    at Object.invoke (http://localhost:60428/dart_sdk.js:191736:7)
    at _engine.EnginePlatformDispatcher.__.invokeOnDrawFrame (http://localhost:60428/dart_sdk.js:171933:15)
    at http://localhost:60428/dart_sdk.js:191477:57
```

**Comment by Quesadeha** [comment]
Turns out I just needed to include Stripe.publishableKey = 'your publishable key' inside of main()
