### ISSUE TITLE
Can't create a payment method

### ISSUE THREAD

**Issue by jgrody** [flutter-stripe/flutter_stripe#87]
**Describe the bug**
The following error is received when attempting to create a payment method:
`e type 'String' is not a subtype of type 'Map<dynamic, dynamic>?' in type cast`

**To Reproduce**
1. Using CardField, enter card information (4242 4242 4242 4242, ...)
2. Once you have the resulting card, attempt to create a payment method

```
// UI
CardField(
  enablePostalCode: true,
  autofocus: true,
  onCardChanged: (card) {
    setState(() {
      _card = card;
    });
  },
),

// assuming we have `card` available from CardField now here:
// card = CardFieldInputDetails(complete: true, last4: 4242, expiryMonth: 12, expiryYear: 34, postalCode: 92103, brand: Visa)

final billingDetails = BillingDetails(
  email: 'email@stripe.com',
  phone: '+48888000888',
  address: Address(
    city: 'Houston',
    country: 'US',
    line1: '1459  Circle Drive',
    line2: '',
    state: 'Texas',
    postalCode: card.postalCode,
  ),
);

// This fails
final pm = await Stripe.instance.createPaymentMethod(
  PaymentMethodParams.card(
    billingDetails: billingDetails,
  ),
);

flutter: e type 'String' is not a subtype of type 'Map<dynamic, dynamic>?' in type cast
```

**Expected behavior**
A payment method object should be created

**Smartphone / tablet**
 - Device: iPhone 12 Pro Max Simulator
 - OS: [e.g. iOS 13, Android 10]
 - Package version: latest
 - [✓] Flutter (Channel stable, 2.0.5, on macOS 11.3.1 20E241 darwin-x64, locale en-US)

**Comment by remonh87** [comment]
@jamesblasco  I did some triage and it only fails on iOS probably we miss the right code there? Can you have a look since I am not an iOS dev.

stacktrace:
```
VERBOSE-2:ui_dart_state.cc(199)] Unhandled Exception: type 'String' is not a subtype of type 'Map<dynamic, dynamic>?' in type cast
#0      MethodChannel._invokeMethod package:flutter/…/services/platform_channel.dart:158 <asynchronous suspension>
#1      MethodChannel.invokeMapMethod package:flutter/…/services/platform_channel.dart:358 <asynchronous suspension>
#2      MethodChannelStripe.createPaymentMethod package:stripe_platform_interface/src/method_channel_stripe.dart:55 <asynchronous suspension>
#3      Stripe.createPaymentMethod package:flutter_stripe/src/stripe.dart:118 <asynchronous suspension>
#4      _NoWebhookPaymentScreenState._handlePayPress package:stripe_example/screens/no_webhook_payment_screen.dart:72 <asynchronous suspension>
#5      _LoadingButtonState._loadFuture package:stripe_example/widgets/loading_button.dart:33 <asynchronous suspension>
```

**Comment by lbk9** [comment]
Any idea roughly of when this fix will be released?

**Comment by jiten-acme** [comment]
This issue still occurs  #122 ?

**Comment by davidbnk** [comment]
This is happening on Android, I'm using the master branch
```
flutter_stripe: 
    git:
      url: https://github.com/flutter-stripe/flutter_stripe
      path: stripe/
```
