### ISSUE TITLE
Error rendering second CardField screen on Android

### ISSUE THREAD

**Issue by tmichaelreis** [flutter-stripe/flutter_stripe#899]
**Describe the bug**
When navigating from one screen with a `CardField` to another, we are seeing the following error on Android: `java.lang.IllegalStateException: The Android view returned from PlatformView#getView() was already added to a parent view.` and the `CardField` widget fails to render properly.

There are no problems in iOS.

**To Reproduce**

```
import 'package:flutter/material.dart';
import 'package:flutter_stripe/flutter_stripe.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        title: 'Minimum Reproduction',
        theme: ThemeData(primarySwatch: Colors.blue),
        home: const CardFieldPage());
  }
}

class CardFieldPage extends StatefulWidget {
  const CardFieldPage({Key? key}) : super(key: key);

  @override
  State<CardFieldPage> createState() => _CardFieldPageState();
}

class _CardFieldPageState extends State<CardFieldPage> {
  final controller = CardEditController();

  @override
  void initState() {
    controller.addListener(update);
    super.initState();
  }

  void update() => setState(() {});

  @override
  void dispose() {
    controller.removeListener(update);
    controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Minimum Repro'),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            CardField(controller: controller),
            ElevatedButton(
                onPressed: _navigateToCardField, child: const Text('New CardField Screen'))
          ],
        ),
      ),
    );
  }

  _navigateToCardField() {
    Navigator.pushReplacement(
      context,
      MaterialPageRoute(builder: (context) => const CardFieldPage()),
    );
  }
}
```

**Expected behavior**
Navigating to a new screen with a `CardField` should display a fresh form with no issues.

**Smartphone / tablet**
 - Device: Pixel 3
 - OS: Android 13
 - Package version: 4.0.0
 - Flutter version: 3.0.5

**Additional context**
Full stack trace:
```
java.lang.IllegalStateException: The Android view returned from PlatformView#getView() was already added to a parent view.
	at io.flutter.plugin.platform.PlatformViewsController$1.createForTextureLayer(PlatformViewsController.java:232)
	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:122)
	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:60)
	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7929)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

**Comment by remonh87** [comment]
I am not sure if this is correct usage of the library since android really relies on  only one instance to be active.  @jonasbark  can you elaborate a bit more on this?

**Comment by jonasbark** [comment]
Indeed the library (or the react native library for that matter) only supports a single instance at a time. Though we may be able to support multiple ones with a few workarounds, which will require further analysis.

**Comment by daviddavis83** [comment]
I am having the same issue. After a user successfully submits a payment they are navigated away to a new page. If they create a new checkout session and navigate to the payment screen the card field form is gone. In debug I am getting the above error.

**Comment by Anonymousgaurav** [comment]
@daviddavis83 did you got any solution?

**Comment by tmichaelreis** [comment]
I'm not certain this is still an issue, but we used a workaround similar to this, using a `CardFormState` provider:

```
import 'package:flutter/material.dart';
import 'package:flutter_stripe/flutter_stripe.dart';
import 'package:provider/provider.dart';

void main() {
  runApp(SafeCardFormExample());
}

class SafeCardFormExample extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        ChangeNotifierProvider(
          create: (_) => CardFormState(),
        ),
      ],
      child: MaterialApp(
        title: 'Test Card Form App',
        home: CreditCardForm(),
      ),
    );
  }
}

class CardFormState extends ChangeNotifier {
  bool _inUse = false;

  CardFormState();

  bool get inUse => _inUse;

  void claim() {
    _inUse = true;
  }

  void release() {
    _inUse = false;
  }
}

class CreditCardForm extends StatefulWidget {
  CreditCardForm({Key? key}) : super(key: key);

  @override
  _CreditCardFormState createState() => _CreditCardFormState();
}

class _CreditCardFormState extends State<CreditCardForm> {
  final _cardEditController = CardEditController();

  void update() {
    if (mounted) {
      setState(() {});
    }
  }

  @override
  void initState() {
    _cardEditController.addListener(update);
    super.initState();
  }

  @override
  void dispose() {
    _cardEditController.removeListener(update);
    _cardEditController.dispose();
    super.dispose();
  }

  void _submit() {
    // Submit card info
  }

  @override
  Widget build(BuildContext context) {
    return Material(
      child: Padding(
        padding: const EdgeInsets.all(8.0),
        child: Column(
          children: <Widget>[
            SafeArea(
              maintainBottomViewPadding: true,
              child: AnimatedContainer(
                duration: Duration(milliseconds: 300),
                child: Stack(children: [
                  SafeCardField(controller: _cardEditController),
                ]),
              ),
            ),
            SizedBox(height: 20),
            ElevatedButton(
              child: Text('Render second card form'),
              onPressed: () => Navigator.pushReplacement(
                context,
                MaterialPageRoute(builder: (context) => CreditCardForm()),
              ),
            ),
            ElevatedButton(
              child: Text('Save'),
              onPressed: _cardEditController.complete ? () async => _submit() : () {},
            ),
          ],
        ),
      ),
    );
  }
}

class SafeCardField extends StatefulWidget {
  final CardEditController controller;
  SafeCardField({Key? key, required this.controller}) : super(key: key);

  @override
  State<SafeCardField> createState() => _SafeCardFieldState();
}

class _SafeCardFieldState extends State<SafeCardField> {
  bool _cardFieldReady = false;
  late CardFormState _cardFormState;
  bool _hasError = false;

  @override
  void initState() {
    Stripe.publishableKey = 'abc123'; // Your Stripe Key
    _cardFormState = Provider.of<CardFormState>(context, listen: false);
    _waitForCardField();
    super.initState();
  }

  @override
  void dispose() {
    if (_cardFieldReady) {
      // Avoid release on load error
      _cardFormState.release();
    }
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    if (_hasError) {
      return Text('Error loading CardForm. Please try again');
    } else if (_cardFieldReady) {
      return CardField(controller: widget.controller);
    } else {
      return CircularProgressIndicator(
        strokeWidth: 2.0,
      );
    }
  }

  _waitForCardField() async {
    var _maxWaitTime = 5000; // 5 seconds
    var _waitTime = 0;
    while (_cardFormState.inUse) {
      if (_waitTime > _maxWaitTime) {
        if (mounted) {
          setState(() {
            _hasError = true;
          });
        }
        return;
      }
      await Future.delayed(Duration(milliseconds: 500));
      _waitTime += 500;
    }

    _cardFormState.claim();

    // Attempt to reload stripe instance
    await Stripe.instance.applySettings();

    if (mounted) {
      setState(() {
        _cardFieldReady = true;
      });
    }
  }
}
```
