### ISSUE TITLE
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(error, lateinit property stripeSdk has not been initialized, null, kotlin.UninitializedPropertyAccessException: lateinit property stripeSdk has not been initialized

### ISSUE THREAD

**Issue by ziagit** [flutter-stripe/flutter_stripe#951]
I want to create stripe token I have a checkout widget as bellow
```
Widget build(BuildContext context) {
    return Scaffold(
      appBar: SimpleAppBar("Add card details"),
      body:  CardField(
                      onCardChanged: (card) {
                        print(card);
                      },
                    ),
      ),
      floatingActionButton: _isSubmitting
          ? circularProgress(context)
          : FloatingActionButton(
              onPressed: () {
                _getStripeToken(context);
              },
              child: Icon(Icons.add, color: Colors.white),
            ),
    );
  }
```
and this is main.dart file
```
import 'package:provider/provider.dart';
import 'package:flutter_stripe/flutter_stripe.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  // set the publishable key for Stripe - this is mandatory
  Stripe.publishableKey = stripeKey;
  runApp(
    MultiProvider(
      providers: [
        ChangeNotifierProvider<OrderProvider>(
            create: (context) => OrderProvider()),
        ChangeNotifierProvider<ProfileProvider>(
            create: (context) => ProfileProvider()),
        ChangeNotifierProvider<NotificationProvider>(
            create: (context) => NotificationProvider())
      ],
      child: Routes(),
    ),
  );
}
```
I get the following error when load the widget
```
+5 ms] E/flutter (13641): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(error, lateinit property stripeSdk has not been initialized,
null, kotlin.UninitializedPropertyAccessException: lateinit property stripeSdk has not been initialized
[        ] E/flutter (13641):   at com.flutter.stripe.StripeAndroidPlugin.getStripeSdk(StripeAndroidPlugin.kt:33)
[        ] E/flutter (13641):   at com.flutter.stripe.StripeAndroidPlugin$onAttachedToEngine$1.invoke(StripeAndroidPlugin.kt:56)
[        ] E/flutter (13641):   at com.flutter.stripe.StripeAndroidPlugin$onAttachedToEngine$1.invoke(StripeAndroidPlugin.kt:56)
[        ] E/flutter (13641):   at com.flutter.stripe.StripeSdkCardPlatformView.<init>(StripeSdkCardPlatformView.kt:27)
[        ] E/flutter (13641):   at com.flutter.stripe.StripeSdkCardPlatformViewFactory.create(StripeSdkCardPlatformViewFactory.kt:24)
[        ] E/flutter (13641):   at io.flutter.plugin.platform.PlatformViewsController$1.createForTextureLayer(PlatformViewsController.java:230)
[        ] E/flutter (13641):   at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:122)
[        ] E/flutter (13641):   at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:60)
[        ] E/flutter (13641):   at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
[        ] E/flutter (13641):   at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
[        ] E/flutter (13641):   at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
[        ] E/flutter (13641):   at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
[        ] E/flutter (13641):   at android.os.Handler.handleCallback(Handler.java:938)
[        ] E/flutter (13641):   at android.os.Handler.dispatchMessage(Handler.java:99)
[        ] E/flutter (13641):   at android.os.Looper.loop(Looper.java:246)
[        ] E/flutter (13641):   at android.app.ActivityThread.main(ActivityThread.java:8653)
[        ] E/flutter (13641):   at java.lang.reflect.Method.invoke(Native Method)
[        ] E/flutter (13641):   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
[        ] E/flutter (13641):   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
[        ] E/flutter (13641): )
[        ] E/flutter (13641): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653:7)
[        ] E/flutter (13641): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:296:18)
[        ] E/flutter (13641): <asynchronous suspension>
[        ] E/flutter (13641): #2      TextureAndroidViewController._sendCreateMessage (package:flutter/src/services/platform_views.dart:1146:18)
[        ] E/flutter (13641): <asynchronous suspension>
[        ] E/flutter (13641): #3      AndroidViewController.create (package:flutter/src/services/platform_views.dart:792:5)
[        ] E/flutter (13641): <asynchronous suspension>
```

**Comment by remonh87** [comment]
please use: [Support: Android initialization error: PlatformException(flutter_stripe initialization failed)](https://github.com/flutter-stripe/flutter_stripe/discussions/538) for support on this issue.
