### ISSUE TITLE
Failed to handle method call when complete payment

### ISSUE THREAD

**Issue by kwstasarva** [flutter-stripe/flutter_stripe#994]
Hello. We are using flutter_stripe 6.0.0. When we try to do a test payment we receive the following error
`
E/MethodChannel#flutter.stripe/payments(10676): Failed to handle method call
E/MethodChannel#flutter.stripe/payments(10676): java.lang.ClassCastException: org.json.JSONObject$1 cannot be cast to org.json.JSONObject
E/MethodChannel#flutter.stripe/payments(10676): 	at com.flutter.stripe.StripeAndroidPlugin.onMethodCall(StripeAndroidPlugin.kt:265)
E/MethodChannel#flutter.stripe/payments(10676): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/MethodChannel#flutter.stripe/payments(10676): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#flutter.stripe/payments(10676): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/MethodChannel#flutter.stripe/payments(10676): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#flutter.stripe/payments(10676): 	at android.os.Handler.handleCallback(Handler.java:938)
E/MethodChannel#flutter.stripe/payments(10676): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#flutter.stripe/payments(10676): 	at android.os.Looper.loopOnce(Looper.java:201)
E/MethodChannel#flutter.stripe/payments(10676): 	at android.os.Looper.loop(Looper.java:288)
E/MethodChannel#flutter.stripe/payments(10676): 	at android.app.ActivityThread.main(ActivityThread.java:7842)
E/MethodChannel#flutter.stripe/payments(10676): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter.stripe/payments(10676): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/MethodChannel#flutter.stripe/payments(10676): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
`
1. Entering number 4242424242424242 into the cardfield.
2. Tapping the confirm button.
3. Observe a failure with the exception mentioned above

**Expected behavior**
The payment to complete successfully

**Smartphone / tablet**
 - Device: Android emulator
 - OS: Pixel 5 API 32
 - Package version: 6.0.0
 - Flutter version 3.3.4

**Comment by remonh87** [comment]
which method are you using confirm payment?

**Comment by kwstasarva** [comment]
Hello @remonh87. Thank you for your reply. We are using the following. 
`  
Future<PaymentIntent> confirmPayment({
    required String paymentIntentClientSecret,
    PaymentMethodParams? data,
    PaymentMethodOptions? options,
  }) async {
    await _awaitForSettings();
    try {
      final paymentMethod = await _platform.confirmPayment(
        paymentIntentClientSecret,
        data,
        options,
      );
      return paymentMethod;
    } on StripeError {
      rethrow;
    }
  }
`

That's a copy paste from your lib

**Comment by remonh87** [comment]
are the options null  in your example?  Can you try to do in case options is null?

```dart
options: PaymentMethodOptions(
        setupFutureUsage:  null
      );
```

I tried to reproduce it in the example app using the webhook payment screen and cannot reproduce it but it looks like sth is wrong.

**Comment by kwstasarva** [comment]
All the following scenarios result in the error I mentioned above.

1. `confirmPayment(
            paymentIntentClientSecret: paymentIntentClientSecret,
            data: data,
            options: null
          );
`
2. `confirmPayment(
            paymentIntentClientSecret: paymentIntentClientSecret,
            data: data,
            options: PaymentMethodOptions(
                    setupFutureUsage: PaymentIntentsFutureUsage.OffSession,
                  )
          );`
3. `confirmPayment(
            paymentIntentClientSecret: paymentIntentClientSecret,
            data: data,
            options: const PaymentMethodOptions(
                    setupFutureUsage: null,
                 ),
          );`

**Comment by kwstasarva** [comment]
@remonh87 Is there anything else needed by your side to look into the issue?

**Comment by remonh87** [comment]
I tried to reproduce it but still am unaible. Can you reproduce it using our example app?

**Comment by kwstasarva** [comment]
@remonh87 I will update to your latest version and try again. Will be back soon

**Comment by kwstasarva** [comment]
The issue seems to be resolved in the latest version of the package. After upgrading to flutter_stripe: 7.0.0 the error is gone. 
Another thing to mention is that in flutter_stripe: 6.0.0 the "Save the card" feature was not working. This is fixed in the latest version as well. Thank you @remonh87
